### ISSUE TITLE
Campaigns Table to Mobile Subscriptions Table Logic Check

### ISSUE THREAD

**Issue by namimody** [DoSomething/quasar#101]
Campaign creation <--- ??? ---> mobile subscription table 

^ figure out that to automate process

**Comment by namimody** [comment]
@sheyd this ticket is investigating why SMS games need to be manually ingested right?

**Comment by namimody** [comment]
@sheyd ^ curious if you had a thought on my question above, thanks!

**Comment by jessleenyc** [comment]
Deprecate -- aaron is working on a chatbot.
