### ISSUE TITLE
Create and Document Process for Setting Up Folks in Hubble via SQL Pro

### ISSUE THREAD

**Issue by namimody** [DoSomething/quasar#107]

**Comment by sheyd** [comment]
Setup instructions in LastPass for internal users and shared with Data Team. @namimody Did you keep a list from our meeting of what users I need to add?

**Comment by namimody** [comment]
@sheyd yes -- do you need names or email addresses

**Comment by sheyd** [comment]
Names, please!

**Comment by namimody** [comment]
James
Hannah
Fantini
Chris
Hilary
