### ISSUE TITLE
KPI Query

### ISSUE THREAD

**Issue by namimody** [DoSomething/quasar#122]

**Comment by Bladt** [comment]
Questions:
* Can someone be on our mailchimp lists (either Do Something Members or International) and not have a UID? The two aforementioned lists have a combined 2,579,0008 email address. 
* The mailchimp_sub table has 2,862,325 entries. Only 2,538,491 match with the user table (inner join on email address). What is going on? Why is this ~40k less than the member lists and 330k less than the mailchimp_sub table?

**Comment by Bladt** [comment]
Mobile Questions:
* the mobile_user_lookup table has 3,016,781 entries where the status is active. the GUI from MC lists 3,065,101 active. Why the discrepancy? Which (if either) is accurate?

**Comment by sheyd** [comment]
@Bladt To answer a few of your questions:

**Comment by Bladt** [comment]
mailchimp_sub table is an all time count, not current subscriptions. should explain the 400k discrepancy.

**Comment by Bladt** [comment]
@sheyd One more question re: email subs:

If a user unsubscribes from email (going into `mailchimp_unsub`, then resubscribes to email (e.g. signs up for a subsequent campaign, comes through Niche) would this user still be included in the `mailchimp_unsub` table?

From ad hoc talks with Dee, this case occurs for about 5-10% of Niche registrants, and could represent on a non-trivial segment of members. On mobile, we have also seen 10%+ of opt out re-opt in at a later point.

cc @namimody

**Comment by sheyd** [comment]
@Bladt yes, they would be, similar to how they stay in the `mailchimp_sub` table. So a de-duped list of the table like we discussed last week would be definitive.

cc @namimody

**Comment by Bladt** [comment]
@sheyd So the `mailchimp_unsub` table is a list of members that have ever opted out, regardless of current status. That makes sense. 

What I don't see then, is an easy way to see who on that list has since go on to re-subscribe. These re-subscribes would appear in both `mailchimp_sub` and `mailchimp_unsub`. With the method we talked about last week, we would not count them as members.

We might need to do some sample of emails on `mailchimp_unsub` and get a rate for the prevalence of the re-sub behavior, and then use this rate in the total member calculation. Not ideal, but the best the current schema can support.

**Comment by sheyd** [comment]
We do have `confirm_time` field, so if you did a compare and date sort of
which is newer between a `mailchimp_sub` and `mailchimp_sub` field
`confirm_time`, that's the last updated status.

On Mon, Jun 13, 2016 at 11:10 AM, Bladt <notifications@github.com> wrote:

> @sheyd <https://github.com/sheyd> So the mailchimp_unsub table is a list
> of members that have ever opted out, regardless of current status. That
> makes sense.
>
> What I don't see then, is an easy way to see who on that list has since go
> on to re-subscribe. These re-subscribes would appear in both mailchimp_sub
> and mailchimp_unsub. With the method we talked about last week, we would
> not count them as members.
>
> We might need to do some sample of emails on mailchimp_unsub and get a
> rate for the prevalence of the re-sub behavior, and then use this rate in
> the total member calculation. Not ideal, but the best the current schema
> can support.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/DoSomething/quasar/issues/122#issuecomment-225610709>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEWehQyeGNE9IYJ5vLZ9ayvMniY3V8joks5qLXLwgaJpZM4IaN4V>
> .
>



-- 
Sena Heydari
Director of Infrastructure Engineering, DoSomething.org
@alisinna

**Comment by Bladt** [comment]
Ah - so if a user re-subs, this will update the `confirm_time` in the `mailchimp_sub` table. Thanks!

**Comment by namimody** [comment]
- [ ] QA testing phase 
- time differential solution for Mailchimp unsubscribes
- mobile app members (meeting with messaging/app/Northstar/data folks)

**Comment by jessleenyc** [comment]
Closing this in favor of a more updated ticket: https://github.com/DoSomething/quasar/issues/214
