### ISSUE TITLE
Questions for Fino Consulting

### ISSUE THREAD

**Issue by namimody** [DoSomething/quasar#126]
@sheyd to put together a list of questions for Fino Consulting so that we are setting up Quasar for success.

**Comment by namimody** [comment]
Questions have been passed along to Matt!

**Comment by sheyd** [comment]
And Matt has passed them on to Fino as of Friday 6/3!

On Mon, Jun 6, 2016 at 1:26 PM, Nami Mody <notifications@github.com> wrote:

> Questions have been passed along to Matt!
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/DoSomething/quasar/issues/126#issuecomment-224027730>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEWehafp0wMFIPKUbqbf5_oNVrtrlIqEks5qJFg5gaJpZM4ImoTG>
> .
>



-- 
Sena Heydari
Director of Infrastructure Engineering, DoSomething.org
@alisinna

**Comment by mshmsh5000** [comment]
Changed the spelling of Fino! For reference: http://www.finoconsulting.com/

**Comment by namimody** [comment]
Ah, my bad!! 🙈  Thanks @mshmsh5000!!

**Comment by sheyd** [comment]
We have a contact at Fino Consulting, and I've shared the questions with him.

**Comment by jessleenyc** [comment]
@sheyd Do we have more questions for Fino that we're waiting to hear back on or can this be closed?

**Comment by sheyd** [comment]
I do have more questions, but this can be closed.
