### ISSUE TITLE
Replace Mobile Subscriptions Table

### ISSUE THREAD

**Issue by namimody** [DoSomething/quasar#127]
Let's think about how we use the mobile subscriptions table, and how we can create a new table that serves all the same purposes but is not riddled with odd information and quirks.

Current Schema:

![image](https://cloud.githubusercontent.com/assets/12396076/15544930/82750234-2268-11e6-9681-08ad96fbac27.png)

**Comment by sheyd** [comment]
This is mostly a Quasar initiative at this point, and implicit in the new platform requirements and guidelines. We have other created tables that meet this data gap.
