### ISSUE TITLE
Backfill all Current SMS Games

### ISSUE THREAD

**Issue by namimody** [DoSomething/quasar#128]
In the past few weeks, we've had a few hiccups with the Mobile Subscriptions table backfill job that runs every two hours. If a job fails and then succeeds, it doesn't correct itself and backfill the two hours that it failed for. (Example: it runs at 6 AM, 8 AM, and 10 AM. If the 6 AM job fails, and the 8 AM job succeeds, we're out the subscriptions that happened between 6 AM and 8 AM.)

We're seeing a discrepancy in numbers between the numbers reported in the Mobile Commons UI and the CSV that the lite query spits out, so we're going to rerun a backfill job since all the following campaigns started, to see if that corrects the numbers.

_format: campaign - nid, run ID with mcid_

less stress text - 6054,6805 with mcid 143027

planet zombie - 6798, 6809 with mcid - 143193

birthday mail - 2461,6817 with mcid - (143907, 143909, 143905)

context clues - 6832,6857 with mcid - 144015

Run backfill since April 1st, 2016

**Comment by sheyd** [comment]
SMS `campaign_importer.py` script has been run. Backfill is starting.

**Comment by sheyd** [comment]
From @mshmsh5000 amazing help, just waiting to confirm final import.

**Comment by namimody** [comment]
@sheyd what's the latest here? thanks!

if the final import is done, could you ask @nmccormick619 to spot check a couple and confirm from the reporting side? thanks!!

**Comment by sheyd** [comment]
This is all done, and Birthday Mail is reporting 👍  numbers multiple days in a row.
