### ISSUE TITLE
Add Context To Jenkin Notifications In Slack

### ISSUE THREAD

**Issue by jessleenyc** [DoSomething/quasar#131]
​_TASK_​
-------------------
#### Ideal Deadline
Thursday 06/09

#### Request
Add more context to Jenkin notifications in slack. If not possible in the integration, then please pin common notifications in the channel with a quick explanation. 

#### Why This Matters/Use Case Example
For people in the slack channel to understand implication of Jenkin alerts.

**Comment by sheyd** [comment]
Added descriptions for main Hubble ETL jobs requiring channel notification with context, MC and MailChimp unsubscribes.
