### ISSUE TITLE
Backfill Mobile Subscriptions Table for Old SMS Campaigns

### ISSUE THREAD

**Issue by namimody** [DoSomething/quasar#133]
#### Ideal Deadline

@jamjensen when would you like to reference this data?
#### Request

After James adds the node ID and run ID to the description fields, we'll need to backfill the mobile subscriptions table.
#### Additional Information

@jamjensen could you fill in the date from when we should start the backfill?
#### Why This Matters/Use Case Example

James is working on calculating reportback rates for campaigns that ran in Q4 2015 and needs accurate sign up counts.

**Comment by namimody** [comment]
@jamjensen is this still something you need? thanks!

**Comment by sheyd** [comment]
@jessleenyc @namimody Moving this back to the Future, since it's been "Up Next" for about 2 sprints now.

**Comment by jessleenyc** [comment]
@jamjensen I believe sam has manually updated all mobile common campaigns with its appropriate NID/RUNIDs. Is there anything else that needs to be done on your end before we run a backfill?More specifically, if we still need to update signup counts and reportback rates?

**Comment by jessleenyc** [comment]
Have to manually ingest for SMS only.

**Comment by jessleenyc** [comment]
Work Sam, product intern, did: https://docs.google.com/a/dosomething.org/spreadsheets/d/14PYwV90rhGRTdSp4-W5_Xqf1tbkAO2l8CxVf2zF7bU4/edit?usp=sharing_eid&ts=57aa3696

**Comment by jessleenyc** [comment]
^^ that doc should have mapping of MoCo campaign ids with run ids.

**Comment by jessleenyc** [comment]
Will we make any decisions differently if we backfilled this data?
