### ISSUE TITLE
Manually Ingest Pack that Ash Up

### ISSUE THREAD

**Issue by namimody** [DoSomething/quasar#136]
_TASK_
-------------------
#### Ideal Deadline

Monday, June 27th 

#### Request

Manually ingest "Pack that Ash Up" -- a new SMS game launching July 1st

#### Additional Information

- campaign NID: 5483
- run NID: 6996
- MCID: 145807

**Comment by jessleenyc** [comment]
@sheyd all IDs are updated!

**Comment by sheyd** [comment]
Ingestion complete!
