### ISSUE TITLE
Gather List of Data Sources w/ all table info

### ISSUE THREAD

**Issue by jessleenyc** [DoSomething/quasar#138]
_TASK_
-------------------
#### Ideal Deadline
06/28

#### Request
Create spreadsheet of master list of data sources w/ Table info for each. 

#### Why This Matters/Use Case Example
This will be helpful when we do our off-site for schema work.

**Comment by jessleenyc** [comment]
Hi @mshmsh5000! Can you review the first column of [this trello board](https://trello.com/b/zMRmqwBg/quasar-versioning) that lists our data sources? We want to make sure no sources are missing and that we're asking the right people (those in parenthesis) for the information we're gathering in preparation for schema planning. cc @bladt @namimody

**Comment by mshmsh5000** [comment]
I added cards for for Quicksilver and Deployments. Thanks!

**Comment by namimody** [comment]
Thanks so much @mshmsh5000!
