### ISSUE TITLE
Investigate Mailchimp Unsubscribe Numbers UI vs. API 

### ISSUE THREAD

**Issue by jessleenyc** [DoSomething/quasar#141]
_TASK_
-------------------
#### Ideal Deadline
End of Sprint

#### Request
Please investigate why mailchimp unsubscribe numbers are different on their UI vs. API.

#### Additional Information

@bladt flagged this when creating the KPI query. Jeff, if you have any additional info please note it here.

#### Why This Matters/Use Case Example
We need reliable numbers and should not have these inconsistencies so we want to figure out how/if they're calculated differently.

**Comment by jessleenyc** [comment]
To summarize, looks like Maichimp’s API (v3) now offers a lot more fields for subscriptions. for example: opt-out & confirmed, so right now we’re trying to figure out what the different fields mean, comparing it to what we were using previously, rethinking our interpretation to figure out why the discrepancy exists.

Jeff is going to check whether there’s a large discrepancy between the dates we used to ingest per day vs now as well.

**Comment by namimody** [comment]
@jamjensen would love your help here -- could you add to this issue a downloaded CSV file of "all reports" from Mailchimp with two tabs, one exactly as you downloaded it and then the second tab where you've deleted rows with subtotals? It would be great to have this for all time (@Bladt approximated 500 rows) but if that's difficult for some reason, then would be great to at least have the last 12 months. Is this something you could share along early next week?

**Comment by sheyd** [comment]
@Bladt Here's the MailChimp API endpoint we're using with sample query parameters:

https://us4.api.mailchimp.com/3.0/lists/{{list-id}}/members?status=subscribed&since_timestamp_opt=2016-06-26T16%3A25%3A14.655297&count=10000&fields=members.email_address%2Cmembers.timestamp_opt%2Cmembers.last_changed&before_timestamp_opt=2016-06-26T20%3A25%3A14.655297

I've obfuscated the list-id for security reasons.

**Comment by sheyd** [comment]
@Bladt Also, assigning this to you since you're running with this at the moment. Tag me if there's anything else I can provide. And the link above is for subscriptions.

**Comment by jamjensen** [comment]
@namimody here ya go! two tabs -- one de-duped, the other as it was downloaded, for all time. Let me know if you need anything else. 

[MailChimp_Reports_Jul_5_2016.xlsx](https://github.com/DoSomething/quasar/files/348716/MailChimp_Reports_Jul_5_2016.xlsx)

**Comment by namimody** [comment]
Thanks a ton @jamjensen! @Bladt -- all yours!

**Comment by jessleenyc** [comment]
Investigating a potential fix - https://github.com/DoSomething/quasar/issues/163

**Comment by sheyd** [comment]
My last 3 re-factoring attempts haven't worked. I'm going to try 2 very straightforward attempts to improve this:

**Comment by jessleenyc** [comment]
Investigation closed -- we are optimizing a fix here: https://github.com/DoSomething/quasar/issues/163
