### ISSUE TITLE
Create Two Tables To Account For Daily Active Members

### ISSUE THREAD

**Issue by jessleenyc** [DoSomething/quasar#144]
_TASK_
-------------------
#### Ideal Deadline
End of sprint

#### Request
Create two additional tables in Hubble that show daily unsub/sub numbers. 
@sheyd please update this description as necessary. 

#### Why This Matters/Use Case Example
This will be used for The KPI Query so we have an accurate member count.

**Comment by sheyd** [comment]
Scripts and tables deployed. Running test Jenkins jobs now.

**Comment by sheyd** [comment]
And... we have a total of 16,434 subscribes?? Either we're getting a metric ton of duplicates, the API results are now coming back as expected, or the data in the array is completely wrong. I'm going to see if I can get some 👴  Taft time tomorrow to sanity check my logic.
