### ISSUE TITLE
Investigate Undercounting Mailchimp #s since 6/21

### ISSUE THREAD

**Issue by jessleenyc** [DoSomething/quasar#145]
_BUG_
-------------------
#### Current Behavior
Current data showing low mailchimp unsubscribe numbers since 06/21.

#### Desired Behavior
This number dropped drastically and we need our numbers to be accurate. 

#### Why This Matters
This effects our member count.

**Comment by sheyd** [comment]
MailChimp import scripts were not iterating over all member counts. Fixed an deployed to production. Backfills completed as well.
