### ISSUE TITLE
Final CSV of vInspired Members

### ISSUE THREAD

**Issue by namimody** [DoSomething/quasar#146]
_TASK_
-------------------
#### Deadline

Friday

#### Request

On June 30th, we’ll send a final CSV to the vInspired team with all users since we began our relationship to the vInspired team.

#### Additional Information

This needs to happen on Friday.

#### Why This Matters/Use Case Example

We are terminating the relationship with vInspired.

**Comment by sheyd** [comment]
Export complete, waiting on @Bladt for person to send dump to.

**Comment by sheyd** [comment]
Sent to Graham Hopgood.
