### ISSUE TITLE
Member Count: Incorporate the New Mailchimp list ID’s into the Data 1.0 import code (international list)

### ISSUE THREAD

**Issue by namimody** [DoSomething/quasar#16]
Right now it’s just pulling in the primary Mailchimp users data, no the the broken out international ID ones, and there’s a significant number of users there (MX, BR, and GL-EN)

**Comment by sheyd** [comment]
@namimody @jessleenyc @Bladt Do we still want to do this for Data 1.0? With the new MailChimp v3.0 ingestion scripts, we can scale this out pretty easily, but it's still focused on Data 1.0. I'd prefer we either re-name this issue or create a new one to address this in Quasar.

**Comment by namimody** [comment]
@sheyd just curious, what would be the time estimate required for this? 

@Bladt @jessleenyc Iooks like the international list = 
![image](https://cloud.githubusercontent.com/assets/12396076/16291082/25c7e55e-38d1-11e6-9231-174b6965d6aa.png)

Currently unsure of how to access the BR and MX lists -- @mnelson338, do you have the login info for the BR and MX mailchimp lists? thanks!

**Comment by sheyd** [comment]
@namimody If the structure and everything else are similar to what we're currently doing, probably an hour or less. If there are any unforeseen complications, unknown. But given everything we know about it, I'm banking on the hour or less.

**Comment by namimody** [comment]
@Bladt this is your call, my thought is no, because it's more scripts to maintain/it is classified as Data 1.0 work, period.
