### ISSUE TITLE
Manually Ingest School Your School

### ISSUE THREAD

**Issue by jessleenyc** [DoSomething/quasar#160]
_TASK_
-------------------
#### Ideal Deadline
Friday July 29th 

#### Request

Manually ingest School Your School -- a new SMS game launching Aug 1

#### Additional Information

Campaign NID - 7043
Campaign Run NID - 7052
Mobile Commons ID - 146607

**Comment by jessleenyc** [comment]
@sheyd just an update that all the IDs needed are now provided above. This has to be set up by EOW because the campaign launches Aug 1. Thanks!

**Comment by jessleenyc** [comment]
@sheyd Sorry for messaging you on a Sunday!! Please set up the ingestion for School For School before midnight!! Thank you!

**Comment by sheyd** [comment]
@jessleenyc Campaign ingestion complete. Enjoy the rest of the (intermittently) rainy weekend!
