### ISSUE TITLE
Looker Authentication for TMI Folks

### ISSUE THREAD

**Issue by jessleenyc** [DoSomething/quasar#161]
_TASK_
-------------------
#### Ideal Deadline
07/21

#### Request
Set up google authentication or an alternative for TMI staff.

#### Why This Matters/Use Case Example
They need to see our data too!

**Comment by sheyd** [comment]
This is ready for testing.

**Comment by sheyd** [comment]
@jessleenyc @nmccormick619 Please have one of our awesome TMI'ers test this out and let me know if it works or there are still problems.

**Comment by sheyd** [comment]
Confirmed working!
