### ISSUE TITLE
Deep Learning on AWS Data Tools and Ecosystem

### ISSUE THREAD

**Issue by sheyd** [DoSomething/quasar#162]
#### Ideal Deadline

Open Ended, but before end of Q3.
#### Request

Watch all these videos for best practices:
https://blogs.aws.amazon.com/bigdata/post/Tx3D3UYOXB9XG6Z/Videos-now-available-for-AWS-re-Invent-2015-Big-Data-Analytics-sessions
#### Additional Information

Lot's of great implementation details for AWS specifically on data warehousing, data lakes, ETL architectures, etc.
#### Why This Matters/Use Case Example

Designing good systems means not repeating mistakes others have made, or following their good ideas.

**Comment by jessleenyc** [comment]
Sena's watched 3 out of 15  videos so far!

**Comment by jessleenyc** [comment]
Goal is to finish by EOY
