### ISSUE TITLE
Transfer ownership for all trello/github/google doc accounts

### ISSUE THREAD

**Issue by jessleenyc** [DoSomething/quasar#166]
_TASK_
-------------------
#### Ideal Deadline
Before Nami Leaves!

#### Request
I know you've been transferring stuff over as they come, but wanted to make sure time is set aside to confirm we're good to go :)

**Comment by jessleenyc** [comment]
@namimody I know these are the very last moments so I'm checking in on this ticket to make sure we're all in order!

**Comment by namimody** [comment]
Hi! All cal invites have been shared, and I commented on the GH issues you tagged me in!
