### ISSUE TITLE
Looker: Investigate duplicate runs appearing in tables w/ different dates

### ISSUE THREAD

**Issue by jessleenyc** [DoSomething/quasar#169]
_BUG_
-------------------
#### Current Behavior
All translations associated with a run are appearing on separate lines in Looker tables. 

#### Desired Behavior
There should only be one line per RunID because the numbers are the same and the repetitive lines are confusing because we don't denote that these are translations.  

#### Steps to Replicate
1. Navigate to campaigns overview
2. Scroll to All Campaigns and you'll see the duplicates. i.e. Barbie Bash run 1 is shown four times with three different start dates (because the translations had different start dates) but all the other information is added together. 

#### Why This Matters
We don't want to deliver confusing or redudant data. 

#### Relevant Screenshots + Links
![screen shot 2016-07-26 at 3 14 18 pm](https://cloud.githubusercontent.com/assets/14931921/17152074/473465ea-5344-11e6-935a-9f85fa63c4d7.png)

**Comment by jessleenyc** [comment]
@nmccormick619 can you write a quick line on what the fix was for this and close the issue out?

**Comment by nmccormick619** [comment]
Though we never pinpointed the source of the issue, we were able to find a fix to the bug by manually unchecking and rechecking the 'Show End Date on Pitch and Action Page' box within Phoenix.
