### ISSUE TITLE
Modify Campaign Loader Script to Support Command-Line Switches

### ISSUE THREAD

**Issue by sheyd** [DoSomething/quasar#17]
Using something like [ cement ](http://builtoncement.com/2.6/dev/quickstart.html), change campaign_loader.py script to accept command-line switches as arguments for script running instead of prompted inputs.

Need to figure out switch order and logic, and modify script to accept array of values.

**Comment by namimody** [comment]
automating campaign ingestion for SMS-component and SMS-only campaigns

**Comment by sheyd** [comment]
This was also mentioned in #19 in better terms. Closing this one out as well.
