### ISSUE TITLE
Looker: Update all instances of Mobile to "SMS"

### ISSUE THREAD

**Issue by jessleenyc** [DoSomething/quasar#170]
_TASK_
-------------------
#### Request
For clariy, please update all dashboards with mobile charts/graphs to says 'sms'. for example, "Mobile Sign-Ups By Day" --> "SMS Sign-Ups By Day"

#### Why This Matters/Use Case Example
This was a question brought up during training and since mobile can be interpreted in many ways, it makes sense to update to SMS for clarity.

**Comment by nmccormick619** [comment]
@jessleenyc I DID IT! AND CLOSED IT!
