### ISSUE TITLE
Update Repeat Verified Dash

### ISSUE THREAD

**Issue by jessleenyc** [DoSomething/quasar#172]
_TASK_
-------------------
#### Ideal Deadline
08/10
#### Request
- Update the repeat verified overview so reportbacks reflect campaigns that the user signed up for within time span on graphs. 
- Update the repeat verified overview so avg days to reportback is filtered on new signups within time frame.
- Add a chart that shows which campaigns are most likely to receive reportbacks. 
- Add comments to the code to explain the logic so we can review with Jeff when he's back. This will be good practice moving forward. 

#### Why This Matters/Use Case Example
This will help us understand the health of our campaigns and make decisions on what to focus on for the remainder of this quarter.

**Comment by nmccormick619** [comment]
@jessleenyc just took a look at the code more carefully - the join is based on both run and uid, so it's only counting reportbacks for that specific campaign. Sorry for the confusion!
