### ISSUE TITLE
Competitions Dash -- Review &  Add Looks

### ISSUE THREAD

**Issue by jessleenyc** [DoSomething/quasar#175]
_TASK_
-------------------
#### Ideal Deadline
08/19 

#### Request
Review the dashboard and please add charts/graphs that would let the impact team see how close they are to achieving these goals: 

30% of competitors who rb in gladiator sign up for another campaign within 7 days
10% of competitors who did not rb in gladiator to sign up for another campaign within 7 days

#### Why This Matters/Use Case Example
This is an impact team KPI that will help them make decision and inform decisions regarding competitions .

**Comment by Bladt** [comment]
@jessleenyc 

For '10% of competitors who did not rb in gladiator to sign up for another campaign within 7 days' ...within 7 days of what? For the 30%, its clear that we are interesting within 7 days of rbing. But for this KPI, there is no RB event to base the calculation off.

Broader thought. Maybe it makes more sense to base both KPIs off additional sign-ups that occur within x days of joining the competition. So if competitions are typically 14 days, then set x = 21 days, which would capture the 7ds after the latest possible rb. Thoughts?

**Comment by jessleenyc** [comment]
@bladt as a compromise, we'll be tracking if members sign up for a campaign 30 & 60 days after their sign up for a competition.

**Comment by nmccormick619** [comment]
@jessleenyc @Bladt just an update on this card --- synced with Andrea regarding the bug - right now, there are people who are signing up for competitions but not making it into gladiator, and so hubble is correctly reporting the number of opt-ins, but not necessarily the number who participated (so, reportback amount might be linked to someone who didn't end up doing the competition)...

It is low priority for engineering, so I have let Chris and Hillary know the status - given the small discrepancy in numbers, I advised Chris to continue using Looker so as to avoid manual work in Gladiator.

With that, these two looks are what we've got left until we can table the competitions dash!

**Comment by Bladt** [comment]
created a pdt that tracks the second most recent sign-up for a user, using this logic: ```      select
        ds1.*, count(*) pos
      from
        dosomething.dosomething_signup ds1
      left join
        dosomething.dosomething_signup ds2
          on ds2.uid = ds1.uid and ds2.timestamp >= ds1.timestamp
      group by
        ds1.uid, ds1.timestamp
      having 
        pos = 2```

**Comment by jessleenyc** [comment]
Sync'd with competitions and have decided that this metric isn't crucial to understanding their performance.
