### ISSUE TITLE
Repeat Verified Dash Updates

### ISSUE THREAD

**Issue by jessleenyc** [DoSomething/quasar#179]
_TASK_
-------------------
#### Ideal Deadline
08/18

#### Request
Add: 
- Current Month Members with _ Sign-Ups in First 30 days
- Current Month Members with 1 + RBs in First 30 days
- % of new web signs up column to Active Campaigns charts (does not sum to 100%)
- % of reportbacks with SMS source

**Comment by jessleenyc** [comment]
@bladt updated this ticket with notes from the meeting.

**Comment by Bladt** [comment]
@jessleenyc 

Added `% of New Sign-Ups` table calculation to the monthly table Looks. 

This was not the ideal solution (i.e. the denominator is total sign-ups from new members, and not total new members in the month). After talking with Nick, there may be a way to do the latter from the aforementioned parenthetical using a date pdt based on months. I.e. have the Total New (excld niche, et al) value tied to a month in a pdt, and then join (on date) this pdt into the explore used to create these Looks, which would result in in every row having the Total New as an accessible piece of data. We still need to explore this, but seems possible in theory.

**Comment by Bladt** [comment]
@jessleenyc Everything on: https://data.dosomething.org/dashboards/18?Date%20Range=12%20months&filter_config=%7B%22Date%20Range%22:%5B%7B%22type%22:%22past%22,%22values%22:%5B%7B%22constant%22:%2212%22,%22unit%22:%22mo%22%7D,%7B%7D%5D,%22id%22:0%7D%5D%7D should be ready for QA.

**Comment by jessleenyc** [comment]
@Bladt 
1) added annotations on the new graphs -- can you please review?
2) Reportbacks Submitted via SMS & % of Reportbacks Submitted via SMS: 
- We didn't actually start using SMS as a reportback source until the very end of July. The reason we're seeing sms rb source for previous months is because of an import we did with rbs that were stuck in MoCo. Because of this, I think we should only show trends starting in August. 
3) Total Reportbacks Pacing -- Is there a way to pull in which day of the month we're into? Just something to make it a bit more clear. Maybe changing the title to say Pacing - Start of Month to Today?

**Comment by Bladt** [comment]
@jessleenyc -- all taken care of. Could not make title dynamic for pacing, so updated content. 

also changed the color for the pacing rbs in first...to better differentiate it

**Comment by jessleenyc** [comment]
@bladt looks good! Let's swap it out with the previous version and get it onto prod. Also, please update the Member with _ Sign-ups to reflect the current and previous month.

**Comment by jessleenyc** [comment]
@bladt let's do this monday!
