### ISSUE TITLE
Setup Presto with Airpal Frontend for Cross Service Data Querying

### ISSUE THREAD

**Issue by sheyd** [DoSomething/quasar#180]
#### Ideal Deadline

Next H(sn)ack Week.
#### Request

Setup Presto (https://prestodb.io) to connect all of our disparate data stores in the Web App layer, and put Airpal (http://airbnb.io/airpal/) on top of it as a front-end.
#### Why This Matters/Use Case Example

Running queries across microservices sucks.

**Comment by jessleenyc** [comment]
for one-off queries, it allows you to query against multiple data endpoints in sqlite. in presto you would define the binding of all data structures. (i.e. querying in gladiator w/ phoenix when gladiator isn't ingested)

Allows us to query without creating an ETL process for everything.
