### ISSUE TITLE
Setup Quasar Infrastructure v0.1

### ISSUE THREAD

**Issue by sheyd** [DoSomething/quasar#185]
_TASK_
-------------------
#### Ideal Deadline
8/31/16
#### Request
Setup all Quasar Infrastructure:
* [x] Setup VPC and subnets
* [x] Setup Encryption Key
* [x] Setup Encrypted 16.04 Base AMI
* [x] Setup Bastion Host
* [x] Setup HA Proxy Server
* [x] Setup Jenkins Ansible Server
* [x] Setup Jenkins Server
* [ ] Setup ETL Nodes
* [ ] Setup S3 Bucket
* [ ] Migrate Looker Server
* [ ] Setup RedShift Cluster

#### Additional Information
* Ensure all playbooks for servers and config are on Ansible.
* Turn off most machines while Sena on vacation 8/31-9/10

#### Why This Matters/Use Case Example
Quasar is getting ready for lift-off!!

**Comment by sheyd** [comment]
@jessleenyc Not that is matters that much, just to keep track of certain changes going into effect, I'm moving the Ansible folders to the https://github.com/DoSomething/tower repo so we can keep all infrastructure automation and server setup code in the same repo and keep environment parity as much as possible. This is based on discussions with @blisteringherb yesterday.

**Comment by jessleenyc** [comment]
Broke out the issues in this ticket into smaller issues.
