### ISSUE TITLE
SMS Only Dashboard 

### ISSUE THREAD

**Issue by jessleenyc** [DoSomething/quasar#186]
_TASK_
-------------------
#### Request
Create an SMS Dashboard for the mobile team. 

#### Why This Matters/Use Case Example
Give us a closer look at how our SMS program is performing and help the team make decisions.

**Comment by jessleenyc** [comment]
Just reviewed with Nick, @bladt putting time on the calendar to review before we do a first pass with freddie/james.

**Comment by jessleenyc** [comment]
@nmccormick619 notes from today's meeting here - https://docs.google.com/document/d/1SfD4981lsamaUhiZV_QJnm9NDXcHDwVKvgk6QD5tefc/edit

**Comment by nmccormick619** [comment]
@jessleenyc I think this is just about ready to go. I need to continue working with James to see how we can be most helpful on his manual tasks and bigger questions, though.

**Comment by jessleenyc** [comment]
@nmccormick619 Reportbacks Resulting from SMS Signups - can you update the label from dosomething_reportback Count of Approved Reportbacks to "Total Count of Approved Reportbacks"? 

I'll send it over to James but let's just make that update before we close the ticket.

**Comment by nmccormick619** [comment]
@jessleenyc sure thing! The labels are super strange in Looker so I had to be a bit hacky and just create a calculation equal to that variable, but works fine for now (and can't break).

**Comment by jessleenyc** [comment]
@nmccormick619 reopening this issue. @bladt had some feedback: 
1) Approved SMS Reportbacks: Makes more sense to put 'count of approved reportbacks submitted via SMS' in a separate graph. We should also consider using a bar graph instead.
2) How are the percents of reportbacks calculated? If we're basing it on the FID then are we overcounting reportbacks?
3) Things to consider: What happens when FIDs for a RB come from both web and sms? Do we end up double counting the RB? options: add a rb category that encompasses 'both' web & sms, base the RB off the first FID source, or instead of reporting RB counts report files received.

**Comment by jessleenyc** [comment]
@nmccormick619:

Additional questions brought up during our sync - 
- Does looker make joins if it doesn't have to? 
- Will data fan out in explore for  web_reportbacks_impact if we join the rb id w/ fid?

**Comment by nmccormick619** [comment]
@Bladt @jessleenyc Circling back on our meeting to make some notes:

The reportback table, when joining with the reportback file table, expands to include all files associated with one reportback. To reconcile the inflation, we have to now be sure to always count distinct RBIDs. The issue we are now facing is that the impact numbers are skewed (inflated) and we are unsure how to count impact numbers for distinct RBIDs within the table.

Currently: the join and the measures including SMS reportbacks are commented out; all numbers being reported are accurate, but SMS dash has been partially deprecated.

What we need to do: Figure out a means of reconciling impact numbers (or of joining in the table one-to-one...PDTs?)

**Comment by nmccormick619** [comment]
@Bladt and I discussed - the impact numbers are not being inflated because we are not joining in the fid table when calculating any impact numbers. The proxy we are using for rb via SMS works for our purposes since we added those count_distinct measures. Going to close this out.
