### ISSUE TITLE
Start using dates table

### ISSUE THREAD

**Issue by jessleenyc** [DoSomething/quasar#188]
_TASK_
-------------------
#### Request
Make use of dates table so we can aggregate data. Good place to start would be on the SMS only dash.

**Comment by nmccormick619** [comment]
@jessleenyc @Bladt Current status with this: 

https://data.dosomething.org/explore/the_all_inclusive/dates?show=data,fields&vis=%7B%7D&query=dfCBFGS

Since they are dimensions we can't graph, but this is a step towards what we want it to look like (eg aggregating all information into one table... I imagine columns like 'email opt outs', 'email opt ins', 'new member signups' etc.

**Comment by nmccormick619** [comment]
Progress!

https://data.dosomething.org/explore/the_all_inclusive/dates?show=vis,data,fields&vis=%7B%22colors%22:%5B%22%2323b7fb%22,%22%234e2b63%22,%22%23fcd116%22,%22%23999%22%5D,%22color_palette%22:%22Default%22,%22type%22:%22looker_line%22,%22stacking%22:%22%22,%22show_value_labels%22:false,%22label_density%22:25,%22legend_position%22:%22center%22,%22x_axis_gridlines%22:false,%22y_axis_gridlines%22:true,%22show_view_names%22:true,%22limit_displayed_rows%22:false,%22y_axis_combined%22:true,%22show_y_axis_labels%22:true,%22show_y_axis_ticks%22:true,%22y_axis_tick_density%22:%22default%22,%22y_axis_tick_density_custom%22:5,%22show_x_axis_label%22:true,%22show_x_axis_ticks%22:true,%22x_axis_scale%22:%22auto%22,%22y_axis_scale_mode%22:%22linear%22,%22show_null_points%22:true,%22point_style%22:%22none%22,%22interpolation%22:%22linear%22,%22hidden_series%22:%5B%22summary_by_day.dosomething_reportback_count_approved%22%5D%7D&query=4RBqpzz&filter_config=%7B%22dates.date%22:%5B%7B%22type%22:%22year%22,%22values%22:%5B%7B%22constant%22:%222016%22,%22unit%22:%22day%22%7D,%7B%7D%5D,%22id%22:0%7D%5D%7D&f%5Bdates.date%5D=2016

**Comment by jessleenyc** [comment]
closing because we don't currently have a use case for it. but will likely use when we have a solid member count.
