### ISSUE TITLE
Break Out Lines #68, #72, and #77 of campaign_loader.py script Into Commented Discrete Logic Blocks

### ISSUE THREAD

**Issue by sheyd** [DoSomething/quasar#19]

**Comment by namimody** [comment]
Is this still something we need to do, @sheyd?

**Comment by sheyd** [comment]
@namimody For the remainder of our time on Hubble, I think manual ingestion will be a better use of my time. It takes about 3-10 minutes per SMS game import now, and and unless we have a month where we launch 100 SMS games, Quasar will supersede this and we're not going to have manual imports (or have them to a minimum) for things like this.
