### ISSUE TITLE
Update Pending RBs logic & add to looker dashboards

### ISSUE THREAD

**Issue by jessleenyc** [DoSomething/quasar#193]
_TASK_
-------------------
#### Request
Update the pending rb logic by using fid status instead of rbid flagged status. Add this the number of pending rbs back to the campaigns overview dash, and make sure the update is also reflected on campaign specific dashes. 

#### Why This Matters/Use Case Example
This is a really helpful number for campaign leads to check to get a snapshot of how quickly reportbacks are being reviewed / coming in.

**Comment by jessleenyc** [comment]
Can we see if a RB has a photo attached?

**Comment by jessleenyc** [comment]
@nmccormick619 & @Bladt thinking about this issue again. Would it make sense to continue basing 'pending' on reportback and if the fid = null, we exclude?

This is the original list of pending reportbacks and it looks like we can check to see if there's an fid. https://docs.google.com/spreadsheets/d/1Z3W_EPKKTRlamrk3mAUPnkw5PAzumKdbyhlb3lnsWPI/edit#gid=1841358361

**Comment by jessleenyc** [comment]
@nmccormick619 can you add a quick update on what ended up happening with this?

**Comment by nmccormick619** [comment]
Ultimately we ended up maintaining our logic given that the issue with the 'status' column is from over a year ago and has since been reconciled. Though some time stamps might be wrong for reportbacks pre-dating say 09/2015 using this column, it's easier than the lift that would require using FIDs.
