### ISSUE TITLE
Kudos + Onboarding Dash in Looker

### ISSUE THREAD

**Issue by jessleenyc** [DoSomething/quasar#195]
_TASK_
-------------------
#### Request
Add Kudos Table to Looker.

#### Why This Matters/Use Case Example
This will help us visualize kudos performance! We just sent a CTA in the campaign digest, would love to see if there was an impact.

**Comment by nmccormick619** [comment]
@jessleenyc started incorporating some high level onboarding stats into this dashboard: https://data.dosomething.org/dashboards/21

**Comment by nmccormick619** [comment]
@jessleenyc Can we reprioritize this // discuss the kudos table more in depth? Onboarding dash is super helpful, but I'm afraid the kudos table requires a ton of different joins and can get messy (do-able, but messy), and I rather not be cluttering our workspace with tables that will have little value to the user... maybe it's time we start thinking about creating a new model? Not sure, but let's discuss IRL

**Comment by jessleenyc** [comment]
@nmccormick619 can you add a graph that displays total kudos given over time (by week)?

**Comment by nmccormick619** [comment]
Done!
