### ISSUE TITLE
Manually Ingest Science Sleuth

### ISSUE THREAD

**Issue by jessleenyc** [DoSomething/quasar#198]
_TASK_
-------------------
#### Ideal Deadline
08/30

#### Request
Ingest Science Sluth - a new SMS game launching 09/01

#### Additional Information
Campaign NID - 3478
Campaign Run NID - 7086
Mobile Commons ID - 147467

#### Why This Matters/Use Case Example
If we don't manually ingest, we won't have accurate mobile commons data in our db!

**Comment by sheyd** [comment]
@jessleenyc @nmccormick619 Can't update this without MCID. Do we have on yet?

**Comment by sheyd** [comment]
Ingested!
