### ISSUE TITLE
Create E-Mail Dashboard

### ISSUE THREAD

**Issue by jessleenyc** [DoSomething/quasar#200]
_TASK_
-------------------
#### Request
Once we have e-mail as a signup source, let's create a look to show e-mail signups over time. 

#### Why This Matters/Use Case Example
This will help the messaging team learn more about the effectiveness of their e-mails. 

#### Additional Info
E-mail Signup source is 'email'

**Comment by jessleenyc** [comment]
@nmccormick619 updated e-mail signup source so we can start working on this dashboard cc: @Bladt

**Comment by nmccormick619** [comment]
@jessleenyc I added two looks to the board SMS Only and changed it to SMS & Messaging so that Kika and James can view it there

**Comment by jessleenyc** [comment]
@nmccormick619 can you add a running total of email signups + % to goal? Their goal is 50,000.

**Comment by nmccormick619** [comment]
@jessleenyc Great - done! Close out if there are no other QA issues!

**Comment by jessleenyc** [comment]
@nmccormick619 just realized the goal would need to start from OCT 1 since it's based on the quarter. Once that's updated we can close the issue :)

**Comment by nmccormick619** [comment]
Got it!
