### ISSUE TITLE
Review Looker 1.0 Documentation

### ISSUE THREAD

**Issue by jessleenyc** [DoSomething/quasar#205]
_TASK_
-------------------
#### Request
@bladt can you take a pass at the looker 1.0 doc? I made some updates based on product team feedback. thanks @nmccormick619 for the initial feedback/suggestions -- I have one more question in there for you. 

https://docs.google.com/document/d/1AyuFFj3ujmPYCB4zZTqqwEIfqyNwBnMF2qnIpQjPJJY/edit
https://docs.google.com/spreadsheets/d/13GKCMAgEU9zqqLsYOWwmcnKND5w8-_N9-Nx8mMffeg8/edit

#### Why This Matters/Use Case Example
This is a resource for looker users throughout the org!

**Comment by jessleenyc** [comment]
@bladt updated links to looker docs above.

**Comment by Bladt** [comment]
@jessleenyc left comments and suggestions.

**Comment by jessleenyc** [comment]
@bladt have a few more questions for you: 
1) Does looker weedkly updates refresh at 12:00am EST?
2) Only saw notes for the FAQ doc and not the updates doc -- were there no comments or just haven't gotten to it?
https://docs.google.com/spreadsheets/d/13GKCMAgEU9zqqLsYOWwmcnKND5w8-_N9-Nx8mMffeg8/edit#gid=0
