### ISSUE TITLE
Thor/Prod db refresh

### ISSUE THREAD

**Issue by angaither** [DoSomething/quasar#21]
- [x] drush cc all
- [x] drush vset dosomething_northstar_url 'https://northstar-thor.dosomething.org/'
- [x] turn on all notices and logs (drush vset error_level 2)
- [x] drush vset message_broker_producer_rabbitmq_host 172.20.100.80

**Comment by namimody** [comment]
Hi @angaither! When do you need this done by? Or did this already happen? (Organizing this repo.) Thanks!

**Comment by angaither** [comment]
@namimody these are steps that sena has to take manually after the prod db gets refreshed into thor. 
so it's based on when he feels like having these happen automatically instead of manually

**Comment by sheyd** [comment]
@namimody Probably about 3 hours total time. I'd like to get this done at tail end of this sprint, or beginning of next sprint.

**Comment by sheyd** [comment]
https://jenkins-thor.dosomething.org/job/Refresh%20Thor%20DB%20from%20Prod/
