### ISSUE TITLE
Resample duplicate ratio for member count

### ISSUE THREAD

**Issue by jessleenyc** [DoSomething/quasar#213]
TASK_
-------------------
#### Request
Resample duplicate ratio. For users that had two accounts, we need to see the ratio that have opted out of one of the accounts. 

#### Why This Matters/Use Case Example
This effects our member count and it's our Q3 KPI goal to get this as accurate as possible.

**Comment by jessleenyc** [comment]
Mobile Users Table -- E-mail Updated?

**Comment by nmccormick619** [comment]
select *
from mobile_user_lookup mul
left join mobile_users mu on mul.phone_number=mu.phone_number
left join mailchimp_unsub muns on muns.email_address=mu.email
left join mailchimp_sub msub on msub.email_address=mu.email
where mul.uid IS NOT NULL
and mu.status='Active Subscriber'
and muns.unsub_time IS NOT NULL
and muns.unsub_time>msub.confirm_time

**Comment by jessleenyc** [comment]
@nmccormick619 according to my notes we actually decided to do a spot test of this ourselves? The concern is that only niche members would have e-mails in the mobile user lookup table right?

**Comment by nmccormick619** [comment]
@jessleenyc I'm not sure - I quite honestly don't know anything about how that table is populated!

**Comment by jessleenyc** [comment]
@sheyd do you have any idea how the mobile user lookup table is populated? We want to see if the email column is updated with all e-mail addresses or if it's only pulling in from specific souces like Niche. This is blocking nick from creating a sampling ratio for our member count so just wanted to see if you were the right person to ask!

**Comment by jessleenyc** [comment]
Since we didn't hit green on member count in Q3 - should we consider looking into this first - https://github.com/DoSomething/quasar/issues/231

**Comment by nmccormick619** [comment]
Done - reiterate process -
____________________________________________________
select *
from mobile_user_lookup mul
where mul.uid IS NOT NULL
and mul.status='Active Subscriber'
order by rand()
limit 100
___________________________________________________________

Add commas to these UIDs, put into query -

select *
from users u
left join users_and_activities.mailchimp_sub_daily ms on ms.email_address=u.mail
where uid IN (UID, UID, UID etc)
and ms.confirm_time IS NULL
________________________________________________________________

Current ratio at 23.6%
