### ISSUE TITLE
Niche Dashboard Requests

### ISSUE THREAD

**Issue by jessleenyc** [DoSomething/quasar#223]
_TASK_
-------------------
#### Request
Niche Dashboard Requests - 
1) Breakdown of reportbacks by source -- interested to see if niche users are reporting back via sms
2) Signups: Niche registration source + email source ( to see if existing niche members are signing up for additional campaigns through DS messaging — weekly do, campaign digest, etc) 
3) % of Niche RB rates compared w/ niche signups

#### Why This Matters/Use Case Example
Questions James is asking to better understand the behavior of niche users.

**Comment by nmccormick619** [comment]
@jessleenyc I assigned this to myself - going to work through Github on Friday!

**Comment by nmccormick619** [comment]
@jessleenyc I made some of these looks, I just have to review them with James to figure out what exactly would be helpful.

**Comment by nmccormick619** [comment]
@jessleenyc reviewed with James! Let me know when you have a minute for some QA - assigning to you before we close out!

**Comment by jessleenyc** [comment]
Added some annotations, closing this tix
