### ISSUE TITLE
Marketing/Fastweb/Members Dash

### ISSUE THREAD

**Issue by jessleenyc** [DoSomething/quasar#224]
#### Request

Let's build out the members overview dash. We definitely want to include: 
- A daily look at signups w/ the most popular co-reg source. 

Some additional ideas:
2) Overall gender breakdown
3) Something with location? -- Top 5 states signups and reportbacks come from?
4) Age breakdowns by signups and reportbacks?

**Comment by nmccormick619** [comment]
This is generally part of the marketing dash I have been working on; see the running copy here:
https://data.dosomething.org/dashboards/16

**Comment by jessleenyc** [comment]
@nmccormick619 @Bladt 
thoughts on having afterschool on here as well since it's something marissa has been QBing?

**Comment by jessleenyc** [comment]
Do we have ..any.. metric for after school?
