### ISSUE TITLE
Quasar Infrastructure: Setup ETL Nodes

### ISSUE THREAD

**Issue by jessleenyc** [DoSomething/quasar#227]
_TASK_
-------------------
#### Request
Set Up ETL Nodes for Quasar Infrastructure. 

#### Additional Information
Original issue here: https://github.com/DoSomething/quasar/issues/185

#### Why This Matters/Use Case Example
Foundational task to getting Quasar up and running!

**Comment by sheyd** [comment]
Waiting on PR approval from Morgan.

**Comment by sheyd** [comment]
💥 DONE! ETL Nodes are LIVE!
