### ISSUE TITLE
Quasar Infrastructure: Setup S3 Bucket

### ISSUE THREAD

**Issue by jessleenyc** [DoSomething/quasar#228]
_TASK_
-------------------
#### Request
Setup S3 Bucket for Quasar Infrastructure. 

#### Additional Information
Original issue here: https://github.com/DoSomething/quasar/issues/185

#### Why This Matters/Use Case Example
Foundational task to getting Quasar up and running!

**Comment by sheyd** [comment]
S3 Bucket and credentials setup. Credentials are in LastPass.
