### ISSUE TITLE
Document Storage Process and ETL Decisions in Wiki

### ISSUE THREAD

**Issue by namimody** [DoSomething/quasar#23]
- [ ] "SMS complement" campaigns (ex. Teens for Jeans)
- [ ] "SMS only" campaigns (ex. Driving Coach)

**Comment by sheyd** [comment]
@namimody Sorry, should have put comment in here:

 Only commentary on https://github.com/DoSomething/quasar/wiki/Data-Storage-&-Processing:-%22SMS-Only%22-Campaigns is this part:
```
Web betas, keyword alphas, and both types of broadcast opt-ins all end up having the option to be a "web alpha" at the end of the experience.
```
