### ISSUE TITLE
Quasar Infastructure: Setup RedShift Cluster

### ISSUE THREAD

**Issue by jessleenyc** [DoSomething/quasar#230]
_TASK_
-------------------
#### Request
Setup Redshift Cluster for Quasar Infrastructure. 

#### Additional Information
Original issue here: https://github.com/DoSomething/quasar/issues/185

#### Why This Matters/Use Case Example
Foundational task to getting Quasar up and running!

**Comment by sheyd** [comment]
Cluster setup on Friday! Just tested connecting to it, and we're golden!

**Comment by sheyd** [comment]
Tested connecting from my laptop. Going to ping @mshmsh5000 for double-verification of cluster being up and running when he gets in.

**Comment by sheyd** [comment]
Matt confirmed running!

**Comment by mshmsh5000** [comment]
Doubly verified! 👍
