### ISSUE TITLE
Research: How to update ETL process to replace mobile commons data with gambit data

### ISSUE THREAD

**Issue by jessleenyc** [DoSomething/quasar#237]
## _TASK_
- Look at gambit db structure
- Would it be feasible for us to not update ETL pipeline until we're in Quasar? (continue pulling in from mobile commons)

**Comment by jessleenyc** [comment]
@sheyd based on dev roundtable -- doesn't seem like we'll need to update anything?

**Comment by sheyd** [comment]
@jessleenyc I think let's keep this pending until things are live next week and we go through a test run.
