### ISSUE TITLE
CSV Output of Sign-Up/Reportback Diff for Gambit Chatbot (Gambot)?

### ISSUE THREAD

**Issue by sheyd** [DoSomething/quasar#238]
#### Ideal Deadline

TBD - check with @jamjensen. Probably 1st week November.
#### Request

As @aaronschachter continues to build out Gambit Chatbot functionality, some of the Messaging functionality is moving out of Mobile Commons. One of the key things is broadcast messaging. Right now this is a manual process in Mobile Commons. With Gambot, this data will be available and posted to Phoenix. So, @jamjensen needs a weekly report exported as a CSV of members who have signed-up for campaigns, but have not reported back to send out weekly broadcast to non-reported back members. 

There are two ways to generate this data:
1.  I can hack together a Jenkins job to run a weekly MySQL CSV export and dump it to a downloadable place like AWS S3. 
2. A more elegant solution would be to potentially have this as a Looker query/dash that James could download as a CSV as needed. 

The one gotcha to the second approach is we'd need a saved week over week list, so queries would have to reflect that data and time range, and I'm not sure we have enough timestamp data in Phoenix to track this, or if we can correlate that from another source. @Bladt @nmccormick619 your thoughts on this?
#### Additional Information

@jamjensen Anything I missed here? 
#### Why This Matters/Use Case Example

SMS engagement is important, mmmmkay?

**Comment by sheyd** [comment]
Clarification from @jamjensen. This ticket is specifically for what we're calling "Reminders", which is a per campaign breakdown of users who have signed up, but not reported back for a campaign. So the CSV export would have to encompass a per campaign breakdown, or potentially each be a different CSV?

**Comment by jessleenyc** [comment]
@nmccormick619 spoke with @jamjensen. Can we create a look that will list all sms users who have signed up but not reportedback? 

Also, can we find the fastest manual process for james to compare these users with users who have opted-out? I can sync with you IRL on this but wanted to leave some notes here.

**Comment by nmccormick619** [comment]
@jamjensen @jessleenyc has this been reconciled as we get ready for next week's broadcast? Is there still work to be done here? please let me know! thanks!

**Comment by jessleenyc** [comment]
Correct -- synced w/ @jamjensen and gambit will be figuring out which members need to receive reminder messages.
