### ISSUE TITLE
Get Answers from Mobile Commons re: Ingestion

### ISSUE THREAD

**Issue by namimody** [DoSomething/quasar#24]
- Is the "First Seen ID" the opt in path or the campaign ID?
- What’s the update on us accessing the database (vs. pinging the API)?
- Can Mobile Commons build something/help with manually subscribing the cohort of people who don’t text in the campaign keyword but express interest in the campaign?
- Is the current version of API the latest version? Are there any changes coming down the pipeline? Is documentation up to date?(edited)
- Can we query the “description” field in a way that is meaningful to us?

**Comment by classicfreddie** [comment]
@namimody emailed Mal and cc'ed you~

**Comment by namimody** [comment]
Is the "First Seen ID" the opt in path or the campaign ID?
- discussion here: https://github.com/DoSomething/quasar/issues/28
What’s the update on us accessing the database (vs. pinging the API)?
- discussion here: https://github.com/DoSomething/quasar/issues/31
Can Mobile Commons build something/help with manually subscribing the cohort of people who don’t text in the campaign keyword but express interest in the campaign?
- MC asked whether we can just have the KEYWORD in the first message. @classicfreddie -- thoughts?
- Is the current version of API the latest version? Are there any changes coming down the pipeline? Is documentation up to date?
- The API is at the latest version. 
There is one change in the pipeline, "Adding MT Status", which may not be necessary if the data warehouse option supersedes it.
We'll announce other future changes before they are released.
The documentation is up to date.

**Comment by namimody** [comment]
@Bladt @sheyd do we have the information we need to answer this question?

- Can we query the “description” field in a way that is meaningful to us?

**Comment by classicfreddie** [comment]
@namimody sent a follow up to mal. we'll wait for his response re: profile first seen. For the broadcast, using a keyword in the first message instead of yes/no is not an option. We've tested this and it causes higher opt out and lower response rate.

**Comment by namimody** [comment]
@sheyd: We can query the mobile commons API for the description field as we want to.

And thanks @classicfreddie!
