### ISSUE TITLE
Update all dashboards from "Approved RBs" to "Total RBs"

### ISSUE THREAD

**Issue by jessleenyc** [DoSomething/quasar#255]
- [x] SMS & EMAIL
- [x] Campaigns Overview
- [x] Campaign Specific

**Comment by nmccormick619** [comment]
@jessleenyc are all teams committed to this? I'm happy to make these changes, but want to make sure campaigns team is aware - I thought they generally used the approved Rbs vs the total rbs to see what kind of queue they have

**Comment by nmccormick619** [comment]
@jessleenyc I changed the campaigns overview dash and only two looks on the campaign specific dash (eg the two trend charts of reportback by day and reportback by month)... I want to make sure things don't get too confusing, can you let me know which looks specifically the campaigns team wants changed, keeping in mind my flag of reporting inaccurate data (eg this campaign had 200 reportbacks but only 100 were approved paints a different picture than showing 200 rbs)

**Comment by jessleenyc** [comment]
@nmccormick619 
- The ask is to change all numbers to total reportbacks, except for tables. 
i.e. keep 'Top 10 approved reportbacks'

**Comment by nmccormick619** [comment]
@jessleenyc Done this week - I'm going to close out!
