### ISSUE TITLE
Create Dev Environment for Quasar

### ISSUE THREAD

**Issue by sheyd** [DoSomething/quasar#256]
#### Ideal Deadline

11/11/16
#### Request

Spec and setup dev environment for Quasar.
#### Additional Information

Need to assess options for RedShift emulation, if any, and how to keep things updated to reflect Quasar environment as easily as possible.
#### Why This Matters/Use Case Example

Right now, the dev process for any Quasar or data engineering job is done very haphazardly by pushing to live environment and testing. There needs to be a standardized way to develop against the environment, especially for @sheyd.

**Comment by jessleenyc** [comment]
@sheyd dev env being setup as needed.
