### ISSUE TITLE
Sync All Hubble DB Tables To Quasar

### ISSUE THREAD

**Issue by jessleenyc** [DoSomething/quasar#258]
@sheyd Please list the tables that require manual inport

**Comment by sheyd** [comment]
I was incorrect in phrasing this, I need to import all the DB's. These include:

- [ ] `mobile`
- [ ] `user_processing`
- [ ] `users_and_activities`

**Comment by sheyd** [comment]
Done. Need to extract some individual tables over that didn't transfer properly.

**Comment by sheyd** [comment]
Transferred to managed MySQL data store.
