### ISSUE TITLE
UK vInspired Data Export Pipeline

### ISSUE THREAD

**Issue by sheyd** [DoSomething/quasar#27]
Salient Details:

1. Per Excel spreadsheet format sent by Graham Hopgood, provide daily diff'd CSV export with our UK Drupal DB as source for bunch of fields null'd.
2. Upload to SFTP Salesforce data store.
3. Automate 1 & 2.

@namimody @Bladt I'll share the CSV via Google Docs since it has some potential security info.

**Comment by sheyd** [comment]
@namimody Talked to @Bladt about this, and it seems to reach the deadline, it's not a good use of either of our times. Ideally Graham Hopgood from UK will write the full query and send it our way. If he doesn't, Jeff and I will have to dig into this to get it out the door.

**Comment by sheyd** [comment]
@namimody @Bladt Good news! Graham is going to send us the query early next week, as there's some export table variable names changes they have to implement anyways, and according to Graham, it's easier if he gets it set on their end and send the final query our way.

**Comment by sheyd** [comment]
@namimody Updated milestone to next sprint and moving to "new issues", since we're waiting on Graham at this point to finish this up.

**Comment by namimody** [comment]
:+1: thanks for the update @sheyd!

**Comment by sheyd** [comment]
Graham sent over the query, and I've finished up the automation to happen daily. Waiting for final confirmation on their end, but our part here is done. Will re-open ticket if there's any more work to be done.

**Comment by sheyd** [comment]
Fixed per Graham's confirmation.
