### ISSUE TITLE
Update User Demographic Script to Python 3 Syntax

### ISSUE THREAD

**Issue by sheyd** [DoSomething/quasar#271]
_BUG_
-------------------
#### Current Behavior

The script https://github.com/DoSomething/quasar/blob/master/etl-scripts/jc_profile_api_test.py, is mostly updated to Python 3 from our ETL scripts repo, but there are some type-casting errors that pop-up when running the job.

#### Desired Behavior

Fully validate and update to Python3.

#### Steps to Replicate

Run the script in Quasar manually.

#### Why This Matters

Our demographic data will be out of date if we don't update this script.

**Comment by jessleenyc** [comment]
@nmccormick619 check how we're getting male/female split

**Comment by jessleenyc** [comment]
Continue to hold on updating this script: 
This hasn't be revisited in a while because it wasn't showing huge actionable insights. Let's look at using Niche for more demo info.
