### ISSUE TITLE
Make Sure Dedicated Analytics MySQL Node is Performant

### ISSUE THREAD

**Issue by sheyd** [DoSomething/quasar#272]
_TASK_
-------------------
#### Ideal Deadline

12/1/2016

#### Request

We've been monitoring performance on the RDS node, and it became quickly clear that some performance issues existed due to secondary indexes not being migrated using the AWS DMS service.

Most of the necessary secondary indexes were manually re-created and queries are performant as expected.

#### Additional Information

If there are continuing issues, a more holistic approach should be taken that involves a downtime:

* MySQL table/index export from Prod.
* MySQL import to Quasar to re-create full table structure.
* Use DMS to migrate over update data perpetually.

**Comment by jessleenyc** [comment]
@sheyd Can we close this?
