### ISSUE TITLE
Disable member counter app

### ISSUE THREAD

**Issue by deadlybutter** [DoSomething/quasar#276]
_TASK_
-------------------
#### Ideal Deadline
This sprint would be ideal

#### Request
Kill the ds-member-counter app for now, should just be a `forever stop app.js` or something along those lines.

#### Additional Information
Product wants more granular control over this.

**Comment by sheyd** [comment]
@deadlybutter Realized when I de-commed the Hubble hosts recently, I already did this I think. What was the URI that we checked to see if it was running or not?

**Comment by deadlybutter** [comment]
@sheyd we never had a URL for it, I think it's still running though. Remember when we had to remake the environment & config?

**Comment by sheyd** [comment]
Yeah, but the servers that were on it, I think I de-commissioned. Let me look around a bit more and figure out if I stashed it somewhere else.

**Comment by sheyd** [comment]
@deadlybutter tested changing the numbers, and we haven't seen any updates in about an hour, confirming that the code was running in the old Hubble DO infrastructure. Closing ticket as this is now resolved. RIP DS Member Counter.

**Comment by deadlybutter** [comment]
RIP 💀
