### ISSUE TITLE
Begin NS <> Quasar User Table Ingestion 

### ISSUE THREAD

**Issue by jessleenyc** [DoSomething/quasar#288]
_TASK_
-------------------
#### Ideal Deadline
10K Records ingested by 02/09

#### Request
Begin ingesting northstar data into the quasar user table. This will test the ETL script and give data a chance to understand how the new data will be coming into the quasar schema. 

#### Why This Matters/Use Case Example
First step in moving off of Phoenix.

**Comment by sheyd** [comment]
Have tracked down 2 bugs so far. Some is regex replacement for first name field, had one with `<script>alert1</script>` as the `first_name`. Fixed that, but now still getting "some strings not converted" from MySQLdb module in Python. Current hypothesis is Northstar stores no values as "None" or "", depending on field, and MySQL requires "NULL". Testing more to track down exact bug.

**Comment by sheyd** [comment]
Made small regex function that fixes the None/NULL issue (well, hypothesis that ended up not being true, but makes the inserts to MySQL a tad more consistent/cleaner) that includes casting vars into strings before returning them. MySQL conversion error still complains, so looking at some of the conversion code that @joshcusano wrote, as well as testing conversion per field.

**Comment by jessleenyc** [comment]
@sheyd can you post an update on the NS infrastructure issue we're experiencing?
