### ISSUE TITLE
Tactical "How" Explanation of How Jeff Pulls Concierge

### ISSUE THREAD

**Issue by namimody** [DoSomething/quasar#29]
cc @Bladt

**Comment by sheyd** [comment]
Documented here per yesterday's meeting.

https://github.com/DoSomething/quasar/wiki/Generating-Concierge-Campaign-Reports---Dr.-Bladt's-Manual-Process

@Bladt @namimody Can both of you make sure it's somewhat readable to you?

**Comment by sheyd** [comment]
This is pretty much deprecated in favor `The QUERY` for Data 1.0. Jeff doesn't need to concierge much anymore for daily reports, only KPI's, and we have #122 to work on that. And if Quasar requires 🍸 style data pulls, I'm doing my job wrong.
