### ISSUE TITLE
ETL Campaign info from Phoenix to Quasar by 02/17

### ISSUE THREAD

**Issue by jessleenyc** [DoSomething/quasar#292]
_TASK_
-------------------
#### Request

- [x] Do necessary setup work for pulling campaign data into Quasar. 
- [x] Set up db connection
- [x] Write scripts for ingestion
- [x] ETL 

#### Why This Matters/Use Case Example
Pulling in campaigns info is an MVP for utilizing quasar in dashboards.

**Comment by sheyd** [comment]
Data imported and in production. Punting on `campaign_url` field until we're in Phoenix Next. Confirmed with Jeff this is acceptable, and can actually be recreated in Looker.
