### ISSUE TITLE
Set up ETL for Rogue 

### ISSUE THREAD

**Issue by jessleenyc** [DoSomething/quasar#293]
TASK_
-------------------
#### Description
- Write ETL Scripts for Rogue so we that we can start ingesting Rogue data. 
 
#### Why This Matters/Use Case Example
Once we write the scripts we're able to begin the backfill of Rogue data in the `campaign_activity` table.

**Comment by jamjensen** [comment]
SH: "break down into two tickets: 1 - test rogue API endpoints; 2 - Set up Rogue ETL"

**Comment by sheyd** [comment]
Steps:
- [ ] Create DS Helper library for logging/string parsing.
- [ ] Create DS MySQL library to handle DB Connections.
- [ ] Create DS Rogue Web Scraper based on QuasarWebScraper
- [ ] Create DS Campaign Activity Parser.
- [ ] Create top-level ETL run script.

**Comment by sheyd** [comment]
Notes and updates on code:
* There are ~13000 records in the `campaign_activity` table in Quasar DB. 
* The API scraper definitely torches the Rogue API. 
* The `bare_str` parser in DS Helper library needs to be updated to handle use-cases where inserting records required changing `None`, or `''` to `NULL` values in DB.

Immediate priorities for tomorrow 5/30:
* Update @jamjensen on records, and make sure he can test.
* Work on improving Rogue API responsiveness when scraping data. Coordinate with @blisteringherb or @pnasrat. 
* Update `base_str` handler/parser and re-test ingestion.

**Comment by sheyd** [comment]
Tagging @mshmsh5000 on IRL conversation with @jamjensen:

This is the first time we've run into the issue of a column we want to have as a primary key will have `NULL` values a good deal of the time. Primary keys can't contain any columns that have `NULL` values, which leaves us with two options:
1. Don't use a primary key, and use `DISTINCT` statements in our LookML/Queries.
2. Use a primary key, but use `''` or blank values, and incorporate that into our queries, so statements that are `NULL` or `''`. 

For now, we're opting to not use a primary key, but @jamjensen will test and see what's ultimately the more maintainable solution going forward.

**Comment by sheyd** [comment]
@jamjensen From further testing of the Rogue API, there are now ~37000 records in the DB table.

**Comment by sheyd** [comment]
Ran backfill overnight, and got about 1.5 million records into `campaign_activity` table.

**Comment by sheyd** [comment]
There's about 3.4 million records in Rogue signups table, so backfill should take a bit over a day to complete as a reference point.

**Comment by jamjensen** [comment]
@sheyd in terms of the work required to set up ETL for Rogue - this issue is complete, correct? 

If so can you post today's Rogue backfill update to #298?
