### ISSUE TITLE
Run Member Count!

### ISSUE THREAD

**Issue by jessleenyc** [DoSomething/quasar#296]
_TASK_
-------------------
#### Request
Now that we have the full NS dataset, verify the query and run member count. 

#### Why This Matters/Use Case Example
GOSH it's a critical goal this quarter to have an accurate member count!

**Comment by jamjensen** [comment]
- first need to have full NS dataset into Quasar

**Comment by jamjensen** [comment]
- Could consist of 1 day to sprint's worth of work 
- SH, JB, NM QA and confirm

**Comment by sheyd** [comment]
Let the member counting begin!

**Comment by mikefantini** [comment]
Blocked by #310
