### ISSUE TITLE
Test New Rogue Data & Complete Checklist

### ISSUE THREAD

**Issue by jessleenyc** [DoSomething/quasar#299]
_TASK_
-------------------
#### Request
Test new Rogue data and flag any issues that blocks us from using the data in Looker. 

#### Why This Matters/Use Case Example
Quasar MVP

**Comment by jamjensen** [comment]
**Comparison of Phoenix + Rogue data:** 
- https://docs.google.com/a/dosomething.org/spreadsheets/d/1uDK79XkA589s1y06lGFo03wX3KuJxCKmPJEzF4VLRKA/edit?usp=sharing

**Comment by jamjensen** [comment]
## Count of total signups grouped by signup_source from `campaign_activity_orig` table:
![image](https://user-images.githubusercontent.com/19572934/27549507-2a1e97ae-5a6a-11e7-849a-9d7017ac9c1d.png)


## Count of total signups grouped by signup_source from rogue prod `signups` table:
![image](https://user-images.githubusercontent.com/19572934/27549559-55ebfdd6-5a6a-11e7-8310-ebd0aaeca4d0.png)


### Observations
- 25,438 more records with source as `null/blank` in rogue `signups` 
- 3,441 more records with source as `campaigns` in rogue `signups`
