### ISSUE TITLE
Come up with data accuracy verification steps.

### ISSUE THREAD

**Issue by ghost** [DoSomething/quasar#3]
Best practice for ETL & Data warehouse: 
- testing your assumptions 
- KPI policy framework of checking ETL processes (i.e. once a week check your input and outputs are accurate -- checking mailchip UI with internal ingestion numbers)

**Comment by jessleenyc** [comment]
@namimody WHAT IS GHOST?

**Comment by namimody** [comment]
@jessleenyc I don't actually know about 👻  -- but @sheyd should!

Also -- I think the point of this card is to create some sort of alert/monitoring system to let us know if numbers change significantly/seem to be inaccurate based on some threshold we've set for that metric.

**Comment by jessleenyc** [comment]
We're doing it! all on our own!
