### ISSUE TITLE
Investigate NS Infrastructure Issue

### ISSUE THREAD

**Issue by jessleenyc** [DoSomething/quasar#303]
TASK
----------------
#### Request
Ideal:
Figuring out core infrastructure issue

Compromises:
- Configuring script to run time-boxed, run for a x amount of time, sleep, run again, etc. 
- Paginate so it runs x-amount, dies, restarts

**Comment by sheyd** [comment]
Further investigation has revealed a fair number of `"PHP message: PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted` errors on the Northstar PHP app server that correlate to the times the ingestion script has been running. I've bumped down the ETL script to use half the max users (down to 50 from 100) and letting the process run again. Would prefer not to up the Northstar max RAM allocation per request, which is already at 1GB. 🤕
