### ISSUE TITLE
Data Analyst should be able to view site_accessed data in Quasar

### ISSUE THREAD

**Issue by jessleenyc** [DoSomething/quasar#306]
_TASK_
-------------------
#### Description 
As a Data Analyst, I want to be able to be able to query last_accessed and last_logged_in date in Quasar so that I can understand the most recent user activity. 

#### Why This Matters
So that we are no longer reliant on Phoenix for user activity AND so that we log site_accessed_data in 4 hour traunches. 

#### Definition of Done

**Given** I want to the view site_accessed_data in Quasar
**When** I query the Quasar user table
**Then** I am able to see logged level site accessed data since December
AND I am able to see site_accessed_data in 4-hour traunches

**Comment by jamjensen** [comment]
Top of the backlog for first sprint of Q2

**Comment by jamjensen** [comment]
- Do we have same monthly active user account for both new/old methods?
