### ISSUE TITLE
QA Member Count

### ISSUE THREAD

**Issue by jamjensen** [DoSomething/quasar#310]
_TASK_
-------------------

#### Request
- Once we run the query (#296), we need to confirm that the member count is correct -- if not, this card should be used to document the investigation as to why it's incorrect. 

#### Additional Information
- JB: "Could take anywhere from a single day's worth of work to an entire sprint." 

#### Why This Matters/Use Case Example
- It's a critical goal to have an accurate member count.

**Comment by sheyd** [comment]
NS ingestion done @Bladt! Let the QA'ing begin.

**Comment by mikefantini** [comment]
QA'ing the member count is a blocker for #296

**Comment by jamjensen** [comment]
I just queried the Quasar `users` table for the number of active MoCo subscribers and returned 3,492,915 which is the same exact number I saw on Wednesday. It's also the same number that's in the `all_moco_users` table.  The MoCo GUI currently displays 3,509,362 active subscribers

How often does the script run to update number of active MoCo subscribers in the quasar `users` table?

**Comment by jamjensen** [comment]
DF: "small number of users due to drupal id conflict... members have same drupal id on more than one accounts, which prevents us from updating them"

**Comment by jamjensen** [comment]
Confirming that the number of active MoCo subscribers in the quasar users table is fluctuating based on live updates to Northstar. The difference between the number of active subscribers in the MoCo UI (3,502,427) and the number of active subscribers in quasar users table (3,495,025) is now 7,402.  

Dave is exploring if the association of multiple drupal_ids to different northstar accounts (and the fact that we're unable to update their accounts) can explain the difference. I've also opened a support ticket with MoCo to see if there's any way a user can end up on their Active Subscriber list without having status = active.

**Comment by jamjensen** [comment]
*Update as of 6/6*
- DF to run through another MoCo backfill to see if we skipped over accounts that we didn't properly handle due to issue of duplicate drupal ids.
