### ISSUE TITLE
Upgrade Northstar MongoDB Infrastructure

### ISSUE THREAD

**Issue by sheyd** [DoSomething/quasar#311]
_TASK_
-------------------
#### Ideal Deadline
3/17/17

#### Request
API scraping Northstar for ETL into Quasar has caused infrastructure load on Northstar Mongo server to get excessive. Testing moving to Mongo Atlas or Compose for better performance.

#### Why This Matters/Use Case Example
Northstar is increasingly used by... everything. Time to upgrade from single server and low-powered instances.

**Comment by sheyd** [comment]
@DFurnes I've imported the Thor DB into Mongo Atlas (let me know if you want me to setup a login for you). I've also updated `.env` with DB_HOST and DB_REPL_SET_NAME commented out values. I think the one code change we need is in [here](https://github.com/DoSomething/northstar/blob/44d7d35d22117d7c0bbcc613b02d2f384544f9a2/config/database.php#L56-L59), and start-up with value `'ssl' -> true`. More options here, but I'm wondering if things will automagically pick-up without additional SSL options like the ones [here](https://github.com/jenssegers/laravel-mongodb/issues/661). Any further thoughts/things I can enable so we can run this easily?

**Comment by DFurnes** [comment]
Woo! 🎉 Looking forward to playing around with this tomorrow!

**Comment by sheyd** [comment]
Backend updates have been successful, and @DFurnes has also added a "turbo" mode to NS we're testing out in Thor that's helping significantly as well: https://github.com/DoSomething/northstar/pull/558.

**Comment by sheyd** [comment]
Currently testing on Quasar and importing data from Thor.

**Comment by sheyd** [comment]
Next steps for this are:

- [ ] Create production cluster.
- [ ] Setup credentials for production cluster.
- [ ] Setup VPC peering for production cluster.
- [ ] Import Production data set during downtime, and swap out Northstar server.

**Comment by sheyd** [comment]
Mongo mirror is currently syncing from Prod Northstar Mongo cluster to Mongo Atlas cluster, and so far real-time syncing is working flawlessly. I'm going to leave it over the weekend, and confirm it continues syncing successfully.

**Comment by jamjensen** [comment]
SH: "create devops ticket, then will close out #311"

**Comment by sheyd** [comment]
DevOps ticket: https://github.com/DoSomething/devops/issues/254
