### ISSUE TITLE
Test Rogue API Endpoints

### ISSUE THREAD

**Issue by jamjensen** [DoSomething/quasar#313]
_TASK_
-------------------
#### Description
- Ensure data formatting from Rogue API activity endpoint is valid so that we can set up ETL for Rogue. 
- Make sure that Rogue API scrapping is performant, as in we're able to fulfill requests in a timely fashion (approximately <5 seconds). 

#### Additional Information
- Must be completed before beginning #293 

#### Why This Matters/Use Case Example
- ETL for Rogue is a necessary part of Quasar MVP

**Comment by sheyd** [comment]
Rogue API tested with various parameters, and looks like data formatting is as expected, and from initial tests, performance is acceptable.
