### ISSUE TITLE
Deprecate the Phoenix user activity log table ETL 

### ISSUE THREAD

**Issue by sheyd** [DoSomething/quasar#316]
_BUG_
-------------------
#### Current Behavior
_The user activity table we generate from Phoenix snapshots doesn't clean up old tables. The ETL job now takes about 8 hours of processing (initially about 5 minutes). Time to chop it back down to size._

#### Description
As a Data Engineer, when I generate the user activity table from Phoenix snapshots, I want to deprecate tables older than 7 days so that the ETL process takes less than 10 minutes. 

#### Why This Matters
This task is important because it will (1) prevent the DB server from spinning useless cycles for data we already have and (2) unblock ETL nodes that are currently blocked from running other jobs. 

#### Definition of Done
**Given** I want to update user activity table
**When** I update the user activity table from Phoenix snapshots
**Then** the ETL process takes less than 10 minutes

**Comment by Bladt** [comment]
@sheyd The Active Member reporting in looker is still dependent on `quasar.phoenix_user_log_poc`

**Comment by jamjensen** [comment]
After a conversation with Sena IRL, since we are prioritizing the ingestion of user activity data from NS, it is no longer necessary to update the Phoenix user activity table. Therefore, we can deprecate the Phoenix user activity log table ETL.
