### ISSUE TITLE
Inaccurate Breakdown of Crash Text Dummy Web and SMS Signups on Looker 

### ISSUE THREAD

**Issue by jamjensen** [DoSomething/quasar#318]
_BUG_
-------------------
#### Current Behavior
- The number of web and SMS signups for Crash Text Dummy (an SMS Game) as displayed on its Looker campaign specific dashboard is incorrect. However, the total number of signups is accurate. 
- The dashboard displays ~1k web signups while Mobile Commons displays over 10k web alphas. The dashboard also displays 22k SMS signups even though there are <50 members who have texted in the campaign keyword and only 13k web betas. 

#### Why This Matters
- When reviewing the campaign on Looker the current display is misleading. This can result in staff members inaccurately reporting campaign performance. 

#### Relevant Screenshots + Links
![image](https://cloud.githubusercontent.com/assets/19572934/24274210/2b932ff8-0ffd-11e7-8e35-c4f2ea2ec202.png)

Link to the dashboard: https://data.dosomething.org/dashboards/8?Run%20Nid=7702&filter_config=%7B%22Run%20Nid%22:%5B%7B%22type%22:%22%3D%22,%22values%22:%5B%7B%22constant%22:%227702%22%7D,%7B%7D%5D,%22id%22:2%7D%5D%7D

Link to the MoCo campaign: https://secure.mcommons.com/campaigns/154987

**Comment by nmccormick619** [comment]
It looks like the sign-ups are hitting the web sign-up table without a source 'sms-mobilecommons', so they're being counted. However, not all of them are being counted as duplicates. Could be a gambit issue? Net count is only slightly off.

**Comment by jamjensen** [comment]
@nmccormick619 going to close this out based on...
