### ISSUE TITLE
Data Analyst able to view members' MailChimp subscription status in Quasar users table

### ISSUE THREAD

**Issue by jamjensen** [DoSomething/quasar#321]
_TASK_
-------------------
#### Ideal Deadline
3/28/17

#### Description
_MailChimp subscription status fields need to be added to Quasar `users` table and ETL'd out using existing MailChimp ETL code._

As a Data Analyst, I want to be able to view members' Mailchimp subscription status in Quasar `users` table so that I can determine DoSomething.org's accurate member count. 

#### Why This Matters
- In order to provide the organization/board/external partners with an accurate member count, we need to first know the number of members that are currently subscribed to our Mailchimp list. In order to know the number of members that are currently subscribed to our Mailchimp list, we need to add every member's MailChimp subscription status to the Quasar `users` table. 
- It's part of our Q1 goals. 

#### Definition of Done 
**Given** I query the Quasar `users` table
**When** I query on the MailChimp Subscription Status field
**Then** I am able to view every member's Mailchimp Subscription status

#### Additional Information
Blocking #310 and #294.

**Comment by jamjensen** [comment]
- SH: "anticipate data tomorrow afternoon."

**Comment by sheyd** [comment]
I have the backfill script running, and will update there's data in the DB.

**Comment by sheyd** [comment]
@mshmsh5000 @DFurnes Can I get both your brain-spaces on this ETL script: https://github.com/DoSomething/quasar/blob/ns-to-users-mailchimp/etl-scripts/mailchimp_subscriber_to_user_table.py? I'm running it now to import the Mailchimp subscribers to Quasar table. Specifically, the way the logic works is it builds up a huge array then does all the DB processing at once. I think this is less desireable for two reasons:

1. Doing a backfill like I'm doing now takes forever to get any useful data in the table, and if it fails via API timeout or anything else, it just dies. 
2. It can consume lots of RAM that never gets cleared. And while not particularly an issue for the ETL instances we use, still something that's just not good systems architecture. 

Caveat is that there's more inline DB processing, and we've seen MySQL shit the bed from too many open connections/files before, but this is 1 request every API response, which take about 500-3000ms, so not too worried about it. I think it might be worth a quick refactor to inline the DB insert per API call. Thoughts/opinions?

**Comment by DFurnes** [comment]
Yeah I think doing incremental inserts into the database is a really good idea. 👍

**Comment by DFurnes** [comment]
> Caveat is that there's more inline DB processing, and we've seen MySQL shit the bed from too many open connections/files before

I'm still a Python novice, but you should definitely be able to re-use the same connection for multiple separate database queries. No reason for one script process to have more than one connection.

**Comment by mshmsh5000** [comment]
I'm confused. Isn't this file already reusing a connection to run many incremental `REPLACE` statements?

In the interest of transactional integrity, I would `db.commit()` within the loop (after each `execute()`) instead of at the end.

**Comment by sheyd** [comment]
@mshmsh5000 @DFurnes Yeah, I think it will re-use. I think I was remembering one of our old scripts that had multi-processing enabled and was spawning a bunch of open connection and not properly closing them.

**Comment by sheyd** [comment]
Quick update for @jamjensen @Bladt We'll probably be better testing this tomorrow. The MySQL query I'm using to update the Northstar records is over-writing certain values we ingested from Northstar. I'm testing the fix for it now and will update the script and this ticket shortly.

**Comment by jamjensen** [comment]
Thanks, Sena. 

Please update us once we're ready for testing. I'd love to help out with that @Bladt.

**Comment by sheyd** [comment]
Script ingestion is working properly. Northstar count will ultimately off by 3055 records since I updated records improperly use `REPLACE` instead of `UPDATE` syntax and nuked all the file fields aside from the MailChimp import ones. 🙄  Deleted the bad records, and will re-ingest on Northstar backfill when I have to re-map the `last_logged_in` field.

**Comment by sheyd** [comment]
Ran into a bug where the mailchimp import is dying on record 199000, not sure if timeout or something else. Updated the script to record where it last left off and proceed from there. lf it continues to fail at the same point, I'll do some more debugging via dumping JSON from the MailChimp API at the exact failure point.

**Comment by sheyd** [comment]
Tracked down the error to there being duplicate emails in the Quasar `users` table. I'm reingesting the entire NS backlog, and also updating the code to make sure if duplicate e-mails exist on querying for Northstar_id, to update both of them with the MailChimp values.

**Comment by sheyd** [comment]
Looks like we're out of the fire here. We're past the error point we kept seeing and data is flowing again.

**Comment by sheyd** [comment]
Will update when ingestion is complete.

**Comment by sheyd** [comment]
Mailchimp Ingestion is complete.

**Comment by sheyd** [comment]
Northstar backfill still on-going.

**Comment by mikefantini** [comment]
From today's update: Northstar backfill is about 70% done. Should be done today.

**Comment by jamjensen** [comment]
@Bladt to be able to test all the records and all fields earliest this afternoon, latest tomorrow.

**Comment by jamjensen** [comment]
There are 300k users who are subscribed to Mailchimp but lack a NS id. These users most likely come from email forms, which didn't require DS.org account for people to be added to our list. 

https://dosomething.slack.com/archives/C0FP51V2T/p1491336457562727

Per Dave's comment in Quasar, @sheyd will create a script that posts email addresses to Northstar. 

https://dosomething.slack.com/archives/C0FP51V2T/p1491336759680216

**Comment by jamjensen** [comment]
Next Steps:
- @sheyd to update when he's completed the MailChimp status (sub/unsub) backfill to Quasar `users` table

**Comment by jamjensen** [comment]
As of 4/24 we are unable to see subscription status for new users since 4/12 in the Quasar `users` table.

**Comment by sheyd** [comment]
There's a separate script that actually updates this. I've re-kicked it off to backfill for 2 weeks. I'll update when it's done.

**Comment by sheyd** [comment]
@nmccormick619 @jamjensen Please check subscriber status now.

**Comment by jamjensen** [comment]
@sheyd seeing up-to-date mailchimp subscription status as well as backfilled statuses for the past two weeks. Thanks!  

Will mailchimp subscription status auto-populate into the quasar users table going forward?

**Comment by jamjensen** [comment]
Documenting this [convo](https://dosomething.slack.com/archives/C0FP51V2T/p1493059519335948) - Mailchimp subscription status for new users should auto-populate in the quasar users table for new users going forward. The last missing piece for determining an accurate member count as it relates to email subscribers are the 2500 email addresses that we do not have in Northstar.

**Comment by jamjensen** [comment]
We do not have mailchimp subscription status for users since 4/24. 

Query: 
```
 select
	email, mailchimp_first_subscribed, northstar_id
from
	users
where
	mailchimp_subscription_status = 'subscribed'
	AND mailchimp_first_subscribed > '2017-04-25' 
```

**Comment by sheyd** [comment]
@jamjensen Looks like the backfill run didn't kick off properly after I ran it last. Will double check and report-back.

**Comment by sheyd** [comment]
@jamjensen Backfill is running. I'm going to take an hour to merge in all the MailChimp and Northstar backfill stuff we've done over the past week, since right now they're running in a pretty hacky way. The code isn't pretty, but it's functional. Will update this when done. This will prevent us from having to worry about backfills constantly.

**Comment by sheyd** [comment]
@jamjensen Please check on subscriber status now. Backfill should be complete.

**Comment by jamjensen** [comment]
@sheyd seeing up-to-date subscriber status. thanks!

**Comment by sheyd** [comment]
@jamjensen Jenkins jobs for this backfill also setup, running hourly. Closing.
