### ISSUE TITLE
Provide James with SQL Access

### ISSUE THREAD

**Issue by jamjensen** [DoSomething/quasar#323]
_TASK_
-------------------
#### Request
- Provide @jamjensen with SQL access. 

#### Why This Matters/Use Case Example
- This would help me better review the structure of the old and new DoSomething databases.

**Comment by sheyd** [comment]
@jamjensen I've got your SSH key added to our proxy box. Coordinating rest of setup with you via Slack.

**Comment by sheyd** [comment]
James has confirmed he has access!
