### ISSUE TITLE
Evaluate User Needs

### ISSUE THREAD

**Issue by namimody** [DoSomething/quasar#33]
We've already brainstormed as a team -- now it's time to get an understanding of what people across the org want when it comes to Quasar. What's the best way to do this?

**Comment by namimody** [comment]
3 strategies:

@sheyd: informal coffees with team leads
@namimody: audit of data requests board
@Bladt: KPIs email

**Comment by sheyd** [comment]
People to Meet With, @namimody please add anyone you think I should meet with:
- [ ] Michaela
- [ ] Ben
- [ ] Lisa
- [ ] Marah
- [ ] Nomes
- [ ] Meredith
- [ ] Andrea
- [ ] Greg (the Original Greg)
- [ ] Chris
- [ ] Marissa
- [ ] Uy
- [ ] Fantini (which I think should be the name of a DS cocktail)

**Comment by sheyd** [comment]
@namimody Was talking to Fantini about this and he recommended two things: consolidating meetings of senior people on teams (like TMI), and also having you in on the meetings to make things more efficient. So look out for invites to come!

**Comment by sheyd** [comment]
@namimody per our discussion this morning, and further talks with @mshmsh5000, handing off all the meetings to you for user needs. I'd like to sit in on a few of the meetings, mostly the one with Ben left on the list, but that's about it. Should I send you the notes I have from my meeting with Michaela to you to format as you like, or would you prefer I transcribe them?

**Comment by sheyd** [comment]
@namimody Also, we should discuss whether user needs notes should go in wiki or a Google Doc, or somewhere else. While generally speaking I'd like everything in this repo, including documentation, it is a public repo (we can privatize it, but I'd prefer not to) that we might not want to put all of our internal notes on. Thoughts?
