### ISSUE TITLE
Create csv for Customer.io

### ISSUE THREAD

**Issue by justkika** [DoSomething/quasar#332]
_TASK_
-------------------
#### Ideal Deadline
April 19, 2017

#### Request
Sergii and I create a list of member attributes and their source to be imported into Customer.io. Most of the fields are existing in Northstar but 4 are existing only in Mailchimp. We want to use these fields to generate a csv of existing member data to send to the Customer.io team for them to import into our account.

What we'll need to do is pull the mailchimp data and northstar data, then match the mailchimp data to the northstar_id by a users email.

There's one small task to address: we have A LOT of dummy dosomething.org emails that are spread out between the product team. Can we somehow exclude this from the import? Happy to ask Customer.io to do this as well if it's too much of a lift.

#### Why This is Important
We need to have the ability to message all of our members on our new messaging platform. Messaging is how we get existing users to come back to site and re-engage so once we switch to Customer.io we'll need all of this data in one place!

#### Definition of Done
Given I visit our customer.io account
When I view a users profile
Then I can see all of the northstar and mailchimp fields with exisiting data for current users.

**Comment by sheyd** [comment]
@jamjensen Just for reference, I talked IRL to Kika about this, and it seems the most expedient way to get the data in a unified fashion to Customer.io is for me to spend a day data massaging and getting everything together in a large CSV that involves stitching together some things from MailChimp, Quasar, and then exporting a final CSV. Short list of steps:
- [ ] Export all fields we need from both main MailChimp list and International list as CSV's.
- [ ] Merge both MailChimp and International CSV's into one larger CSV.
- [ ] Import CSV into MySQL table that has every CSV field mapped, with a NULL valued leading `northstar_id` column.
- [ ] Via query or script, lookup and match `northstar_id` to `email` address from imported CSV, and populate `northstar_id` into MySQL table accordingly.
- [ ] Export populated and mapped `northstar_id` to Mailchimp data table as CSV and send to customer.io.

**Comment by justkika** [comment]
Also, @sheyd we'll want these existing Northstar fields in the "import" sheet to be able to send them all of this. In the future we'll be sending new user data from Northstar via blink and will want all of these fields: https://docs.google.com/a/dosomething.org/spreadsheets/d/1UHZAMy0suu7da-pTVAIznIFrMAoktVplMrwuP-pxJIo/edit?usp=sharing

**Comment by justkika** [comment]
@sheyd Is this something that we're still on track to complete this week?

**Comment by jamjensen** [comment]
@sena spoke with @justkika irl -- let's keep #333 as our priority, then take this on once we move c.io data queuing mechanism to production.  Does that make sense to you?

**Comment by Sena** [comment]
@jamjensen I didnt.

**Comment by jamjensen** [comment]
@sena apologies for tagging you, wrong user.

**Comment by sheyd** [comment]
@jamjensen @justkika Yep, makes total sense to me!

**Comment by sergii-tkachenko** [comment]
More info on the CSV. Here's the example: https://docs.google.com/spreadsheets/d/1So8OiddywFEPYY9Kq1jK-sfFTcN6mrUyT_eXcQ92WTE/edit#gid=0

Transformations needed to happen:
- Rename `mobilecommons_status` to `mobile_status`
- Rename `mobile` to `phone`
- Boolean `unsubscribed` fields, format `TRUE` / `FALSE`
- Lowercase `MEMBER_RATING`
- Rename `UNSUB_TIME` to `unsubscribed_at`, transform to unix timestamp
- Transform to unix timestamp: `created_at`, `updated_at`, `last_authenticated_at`, `birthdate`

**Comment by sergii-tkachenko** [comment]
TODO: make sure transformed birthdate resolves to correct date, as unix timestamp doesn't include timezone data.

**Comment by sheyd** [comment]
Exports completed from MailChimp, downloading and massaging them together now, then will do DB import.

**Comment by jamjensen** [comment]
**Thoughts/questions from convo w/ Sena:**
- When c.io imports the csv will it send out web hooks to update customer_io_subscription_status in quasar.users?  If it does, we should let Sergii know so that it doesn't overload Blink. If it does not, how will Quasar (the team) capture subscription status -- transfer the last known good state from Mailchimp? 
- We'll need to update quasar.users to capture members who became active on our Mailchimp list between the csv export date and c.io launch date.

**Comment by sheyd** [comment]
Importing the largest subscribe contingent now. The new staging tables for the imports are in the Quasar DB. Will work on final table today.

**Comment by sheyd** [comment]
Final exported table format.

**Comment by sheyd** [comment]
Putting in table export construction steps here:
- [ ] Import Northstar records to `customer_io_export` table with matching fields required as source.
- [ ] Add index to `e-mail` field in `customer_io_export` table for matching import from Mailchimp staging tables.
- [ ] Import associated MailChimp tables and columns to `customer_io_export` table based on matching e-mail address.
- [ ] Add index to `id` field in `customer_io_export` table to match on Northstar ID for next step.
- [ ] `mongoexport` from Prod Northstar fields as CSV with Northstar ID and interests as fields.
- [ ] Import CSV that contains `interests` to `customer_io_export` table based on Northstar ID (or more likely use intermediary table to import then match/ingest based on Northstar_id)
- [ ] Change all datetime fields to unixtime.
- [ ] Merge all sub/unsub fields to an "unsub" boolean true false column.
- [ ] Get sign-off from Sergii/Kika
- [ ] Export the thing and give to Customer.io!

**Comment by sheyd** [comment]
@jamjensen @justkika @sergii-tkachenko I've shared a Google Folder with you all that we can use to securely share the export with Customer.io. You have edit privileges to add them as users to access the CSV. Let me know when they've downloaded it, and we can revoke access.

**Comment by sergii-tkachenko** [comment]
@sheyd I've downloaded it, will take a look and get back to you.

**Comment by sergii-tkachenko** [comment]
I have a concern about `updated_at` and `birthdate`:

1. `updated_at` falls back to 0, which essentially will render it as `Jan 1 1970`. Should you better skip replace it with an empty string?
2. `birthdate` has time part, `00:00:00` and it should be just the date part, verbatim as it's on Northstar, example `1997-02-27`, not `1997-02-27 00:00:00`

**Comment by sergii-tkachenko** [comment]
Also, do we have a response for interests, @justkika?

**Comment by sergii-tkachenko** [comment]
Critical: per latest revision of ["Customer.io user data sources"](https://docs.google.com/spreadsheets/d/1UHZAMy0suu7da-pTVAIznIFrMAoktVplMrwuP-pxJIo/edit#gid=1281653021), phone should not be exported.

**Comment by sheyd** [comment]
Re-opening pending some further updates to CSV.

**Comment by sheyd** [comment]
@justkika @sergii-tkachenko @jamjensen New file in Google Drive folder replacing the old one. It's gzip'd, so download for inspection.

**Comment by jamjensen** [comment]
@sheyd are we good to share the folder with c.io?

**Comment by sheyd** [comment]
Haven't gotten final confirmation from @justkika and @sergii-tkachenko. If they sign off then we're 💯

**Comment by sheyd** [comment]
@sergii-tkachenko has signed off with one error that I've fixed and re-exported. The new export in the Google Drive folder has the latest export and should be up to date. @sergii-tkachenko @justkika @jamjensen Let's send the link off the C.IO!!!

**Comment by justkika** [comment]
@sheyd @jamjensen @sergii-tkachenko Sent them the link to the folder!!!!! Last piece is the small subset + deploying Northstar to production -- then we are GTG on getting this shipped!!

**Comment by jamjensen** [comment]
@justkika does customer.io have everything they need?

**Comment by sheyd** [comment]
Latest CSV uploaded.

**Comment by jamjensen** [comment]
*Update as of May 12 at 7:30pm* 
- Brandi is unable to import the csv because there still instances of \" in the file. However she has offered to get it done tonight if possible. Waiting on @sheyd to respond.

**Comment by jamjensen** [comment]
*Update as of May 13 at 1:00pm* 
- Brandi was able to process all of the csv except for ~500 users. 

@sheyd Can you please update this issue with the steps you're taking to address the users that Brandi was unable to process?

**Comment by jamjensen** [comment]
*May 19th* 
Need to send Brandi: 
1. Diff between May 2nd (date of MC export) until we went live (May 11) 
2. 500 users that c.io was unable to process

**Comment by jamjensen** [comment]
1. James to send Sergii a csv of Northstar IDs for all users created between May 2nd and May 11th.  Sergii will ingest the csv, which will then send webhooks to update c.io status in `users`. 

2. Sena to investigate who these 500 users are and why Brandi was unable to process them.

**Comment by jamjensen** [comment]
Sergii now has the csv and the remaining work to provide users created between May 2nd and May 11th with c.io status in `users` will be tracked on the O'Doyle card: 
https://www.pivotaltracker.com/story/show/145875683/comments/172074479
