### ISSUE TITLE
Email MC re: Warehousing Timeline

### ISSUE THREAD

**Issue by namimody** [DoSomething/quasar#34]

**Comment by sheyd** [comment]
Mail e-mailed. Waiting on response for next steps.

**Comment by sheyd** [comment]
Exchanged possible options with Mal about tech setup. Waiting on his response.

**Comment by namimody** [comment]
@sheyd any update on this? Thanks!

**Comment by sheyd** [comment]
Yes! Mal responded, and I let him know about us setting up the test environment. I'm supposed to sync with him early next week after I have the test environment setup.

**Comment by namimody** [comment]
Captured in other tickets.
