### ISSUE TITLE
Data Analyst able to view c.io status for members added to mailchimp between date of csv export (May 2) and May 15

### ISSUE THREAD

**Issue by jamjensen** [DoSomething/quasar#344]
_TASK_
-------------------
#### Description
As a Data Analyst I want to be able to view the c.io subscription status of the members who were added to our mailchimp list after the date we exported the csv (May 2nd) until May 15th (date we go live with c.io) so that we can have an accurate understanding of the number of people that are active on our mailing list. 

#### Why This is Important
So that we can have an accurate member count. 

#### Definition of Done
**Given** Sena transfers c.io subscription status from mailchimp
**When** We query quasar user for c.io subscription status 
**Then** We're able to see c.io subscription status for members added during the time period listed above. 

#### Additional Information 
- expect 2-5k new accounts created

**Comment by sheyd** [comment]
@jamjensen Just ran the updates this morning. Can you query against c.io subscription status in users table and let me know if you see any glaring disparities between that count and MailChimp counts we currently use as sources in Looker?

**Comment by jamjensen** [comment]
After reviewing with @nmccormick619 we think there's 3 issues affecting validity of user subscription status: 

(1) 72,866 members with mailchimp_subscription_status = subscribed AND c.io_subscription_status = unsubscribed. 

- Number of members with mailchimp_subscription_status = subscribed: 3,007,268
- Number of members with customer_io_subscription_status = subscribed: 2,934,402

@sheyd I spot checked several of the users with differing mailchimp and c.io subscription statuses in mailchimp and for each one they appeared as subscribed to the `International` list and unsubscribed to the `Do Something Members` list.  

(2) We're seeing `unsubscribed` = FALSE for every single user. 

(3) C.io subscription status is unsubscribed AND mailchimp subscription status is NULL for ~700k users  
- Query:
 ```select u.email, u.customer_io_subscription_status, u.mailchimp_subscription_status, c.unsubscribed
from customer_io_export c
left join users u on u.email=c.email
where c.unsubscribed=FALSE
and u.customer_io_subscription_status='unsubscribed'
and u.mailchimp_subscription_status IS NULL
and u.email IS NOT NULL ```

**Comment by sheyd** [comment]
Point 2 is fixed. Re-ran the update status on the `unsubscribed` columns based on the original MailChimp list imports.

**Comment by sheyd** [comment]
Point #3 is *not* a valid comparison. The users table and customer_io_export table are not directly comparable. The users table is up to date every hour or so, whereas every info piece of customer_io_export is from export last week.

**Comment by sheyd** [comment]
Also same for point #1.

**Comment by jamjensen** [comment]
As of this afternoon customer.io is live, which means we're sending new users and status updates to customer.io. 

We need to confirm if we're seeing customer_io_subscription_status being updated for both existing and new users in the quasar users table. If we're able to view customer_io_subscription_status for all users created between today's date (May 11) and the date we're no longer sending new users to mailchimp (May 15) in the quasar users table then we won't have to transfer mailchimp_subscription_status to c_io_status for every member.

**Comment by sheyd** [comment]
Long-running consumer job setup and will restart on failure.

**Comment by jamjensen** [comment]
Update on Quasar ingesting c.io subscription status:
1. Subscription status appears in `users` when an existing member updates their status
2. Subscription status does not appear in `users` for new users. Their email address appears in `users` (because we are ingesting the record from Northstar); however, we are not yet ingesting their c.io subscription status.  Confirmed with Sergii and Sena IRL that the new user's subscription status is entering the blink queue as the proper event type (`customer_subscription`). Sena is currently looking into why we aren't ingesting status for new users.

**Comment by jamjensen** [comment]
*Update as of May 12 at 7:30pm*
- still unable to see customer_io_subscription_status in the Quasar users table for new users

**Comment by jamjensen** [comment]
*Update as of May 13 at 1:00pm* 
- still unable to see customer_io subscription status in the Quasar users table for new users. 
- 2,000 users created since May 2 that have legitimate email but lack both c.io status and mailchimp status. 
- 2,405 users created since May 2 that have legitimate email but lack c.io status
``` 
select
	count(*)
from
	users
where
	email IS NOT NULL
	AND
	email NOT LIKE '%mobile%'
	AND
	email NOT LIKE '%import%'
	AND 
	mailchimp_subscription_status IS NULL
	AND
	customer_io_subscription_status IS NULL
	AND northstar_created_at_timestamp >'2017-05-02 00:00:00'
```

**Comment by jamjensen** [comment]
*May 19th* 
1. We're updating c.io subscription status for new users 
2. For the 2k users that don't have c.io or MC status 
   - [ ] James to check if they're in the final MC exports
   - [ ] (if don't exist in MC exports) we need to track down where their email address are and find out truth of status
3. For the 2,405: 
   - [ ] James to generate a csv of the 2,405 users 
   - [ ] Sena to find MC status and append to May 2nd - May 11th new user diff and send to c.io.
