### ISSUE TITLE
Data Engineer should upload a csv (snapshot) that will transfer all members' Mailchimp status to their c.io subscription status  

### ISSUE THREAD

**Issue by jamjensen** [DoSomething/quasar#345]
_TASK_
-------------------
#### Description
As a member of the data team I want to be able to view the c.io subscription status for everyone on our mailchimp list so that I am able to produce an accurate member count.

#### Why This is Important
We need to have a subscription status (whether they are subscribed/unsubscribed) for every member on our customer.io list. Since c.io is unable to send web hooks that would update c.io subscription status in quasar.users when they import a csv of our users, we need to upload a csv of with the latest mailchimp subscription status that we can then transfer over to c.io status.  

#### Definition of Done
**Given** We're able to get all of the users out of mailchimp
**When** We query the quasar users table for number of users subscribed to c.io
**Then** We're able to see the same number of users (or more) as we would on our mailchimp list

**Comment by jamjensen** [comment]
Earlier today (Friday) Kika pulled a csv for each list we have in Mailchimp. She will do so again on Sunday to make sure that we have subscription status for every single email address, including those added to Mailchimp before deadline day (May 15).

**Comment by jamjensen** [comment]
Once C.io begins importing the csv (#332), we'll know whether or not they're able to send web hooks, which will provide us with consistent subscription status data. If they're unable to send us web hooks, we'll have to transfer the last known mailchimp subscription status from the CSVs to the customer.io subscription status in `users`.

**Comment by jamjensen** [comment]
*Update as of May 13 at 1:00pm* 
- Quasar was able to process c.io web hooks and update the subscription status of existing members in the `users`table.  However, we were not able to update subscription status for new users -- accounts that were created since the day we made the customer_io_export table (May 2) -- in the `users` table. Sena is working to fix this issue (#344).  
- The subscription status for all new users does not exist in customer.io so, for these users, I think we should transfer their subscription status from the last Mailchimp csv to both Customer.io and `users`. @sheyd thoughts? 
- There are 2,934,128 users  with c.io status = subscribed in the `users` table and 3,008,018 users with mailchimp status = subscribed. This means that there are 73,890 users who are subscribed to our mailchimp international list but unsubscribed on our mailchimp main list. This is due to the fact that when we created a table for the customer.io csv export, the table transferred the user's subscription status from the mailchimp main list as their customer_io_subscription_status. They are listed as unsubscribed in customer.io.

**Comment by sheyd** [comment]
A code bug was causing queue processing to exit and not properly requeue non-parsable messages without Northstar ID. I deployed hotfix #350 which backs up the data to another DB table in Quasar that we can backfill from later.

**Comment by jamjensen** [comment]
*Update as of May 15 at 3pm*
The diff between number of records in `users` with mailchimp_subscription_status as 'subscribed' and customer_io_subscription_status as 'subscribed' is 79,781. This is due to three reasons: 
1. ~70k members were subscribed to the MC international list but at some point unsubscribed from the MC main list.
2. ~5k users created accounts since the MC export (May 2nd) and were never given c.io subscription status. (see Sena's comment above) 
3. ~4 users have unsubscribed since our team made the switch to populating mailchimp_subscription_status in the quasar.users table. If a member unsubscribed from our Mailchimp list we do not update their mailchimp_subscription_status to be 'unsubscribed'. We (Jeff, Nick, Sena + James) knew we would temporarily be overcounting the total number of active members. But made the decision to do so because we knew we would be able to update subscription status in `users` once we moved to c.io.  Prioritizing the switch to c.io was a more productive use of our time than trying to update mailchimp_subscription_status.

**Comment by sheyd** [comment]
I've setup a local cron job on one of the ETL nodes to update the users table from the backlog table every 10 minutes. Did this a truly temporary solution so we can focus on getting the re-publish code fix out.

**Comment by jamjensen** [comment]
Done - we've successfully transferred c.io status from the MC final export. Diff in users that are lacking c.io subscription status and that are not in c.io is captured in #344.
