### ISSUE TITLE
Invalid Message derails Quasar ingestion of c.io data

### ISSUE THREAD

**Issue by jamjensen** [DoSomething/quasar#346]
_BUG_
-------------------
#### Current Behavior
- When using blink as a queuing mechanism to ingest c.io data into quasar, a specific type of invalid message prevents quasar from ingesting the queue. 

#### Desired Behavior
- This type of invalid message should not derail ingestion of c.io data to quasar but rather the process should be able to continue .

**Comment by sheyd** [comment]
This was fixed in PR #350 hotfix. Closing.
