### ISSUE TITLE
Account for all Users who Join DS not Through a Campaign

### ISSUE THREAD

**Issue by namimody** [DoSomething/quasar#35]
Texting JOIN to 38383, Niche, etc.

Set up 30 min meeting.

**Comment by jessleenyc** [comment]
@namimody I believe we're tracking this already, can you confirm?

**Comment by namimody** [comment]
@jessleenyc I think you're correct that it's in the KPI dash, but would be good to double check with @Bladt!

**Comment by jessleenyc** [comment]
@bladt do we account for users who join DS not through a campaign in the KPI dash?
