### ISSUE TITLE
Expose "last accessed at" timestamp in Northstar.

### ISSUE THREAD

**Issue by DFurnes** [DoSomething/quasar#361]
_TASK_
-------------------
#### Ideal Deadline
Soon.™

#### Description
We want to know a user's `last_accessed_at` timestamp on their Northstar profile, so we can easily ingest that information into our data warehouse to track monthly active users. There are a few steps involved here:

- [x] Update user's `last_accessed_at` when granting token in Northstar (DoSomething/northstar#591).
- [x] Optimistically refresh expired access tokens in Phoenix (DoSomething/phoenix#7351)
- [ ] Optimistically refresh expired access tokens in Gateway (…)

This will give us "last accessed" information across any services (so not _just_ legacy Phoenix, like the `accessed` column in Hubble). In the future, we can tie this in with improved analytics that we're sending to Customer.io for more granular timestamps.

#### Why This is Important
This is important for tracking our MAU metrics.

#### Definition of Done
**Given** a service that authenticates users via Northstar
**When**  user visits that service in a web browser
**Then** their `last_accessed_at` timestamp should be updated

#### Additional Information
References #306.

**Comment by jamjensen** [comment]
@DFurnes thanks for taking this on!  Safe to close, right?

**Comment by DFurnes** [comment]
I still haven't made the updates to do this in Gateway apps (Phoenix Next, etc.), so probably worth keeping open for now. I'll wrap that up after staff retreat.

**Comment by jamjensen** [comment]
@DFurnes have you exposed `last_accessed` info across any service (including Gateway apps)?  And if so safe to close this issue out?

**Comment by DFurnes** [comment]
Nope. Gateway `last_accessed_at` timestamps are still pending, hoping to get that in this week. Right now the `last_accessed_at` column should be equivalent to Phoenix Ashes's `access` column for any recent visits.
