### ISSUE TITLE
Update Northstar User Ingestion Script to Ingest Last Accessed Field

### ISSUE THREAD

**Issue by sheyd** [DoSomething/quasar#369]
_TASK_
-------------------
#### Ideal Deadline
6/27/17.
#### Description
The `last_accessed` field is no accessible from the Northstar users API endpoint. I need to update the Northstart ingestion mapping to include this field.

#### Why This is Important
Last accessed date will allow us to get a much clearer picture of user activity and flow through our system.
#### Definition of Done
**Given**
Northstar users API access last_accessed field is available.
**When**
The Northstar->Quasar users table ETL ingestion script runs.
**Then**
Last accessed field is available to use in Quasar users table.
#### Additional Information
#361

**Comment by sheyd** [comment]
* [ ] Add column name to ETL Doc.
* [ ] Add column to `users` table.
* [ ] Update ETL code to ingest new code.
* [ ] Backfill ?

**Comment by jamjensen** [comment]
@sheyd would this also pull in `last_logged_in`?

**Comment by sheyd** [comment]
@jamjensen We already pull that in via code, we just haven't run a full backfill to populate all those entries from Northstar.
