### ISSUE TITLE
Create opt-in ID (unique), opt-in description, MCID, MCID Description, NID, RID Table

### ISSUE THREAD

**Issue by namimody** [DoSomething/quasar#37]
After https://github.com/DoSomething/quasar/issues/9 is finished, create a table to display associations between opt-in ID, MCID, NID, and RID. Unique key: opt-in ID.

**Comment by sheyd** [comment]
@namimody Removing blocked tag.

**Comment by sheyd** [comment]
Table created with primary key using the following commands:
```
CREATE TABLE mobile_campaign_id_lookup (opt_in_path_id BIGINT, opt_in_path_id_name VARCHAR(255), mobile_campaign_id BIGINT, mobile_campaign_id_name VARCHAR(255), nid BIGINT, run_nid BIGINT);

ALTER TABLE mobile_campaign_id_lookup ADD PRIMARY KEY(opt_in_path_id);
```

**Comment by sheyd** [comment]
@namimody table created successfully. In consultation with @Bladt we added a few more columns to reflect `opt_in_path`  and `mobile_campaign_id` names that we get back from Mobile Commons that are useful to query on. 

Next questions:

1. Do we wait till we have MC test data to see if populating things makes sense from the MC database or use API scraping which is a known quantity right now.
2. If we go with the latter approach, I'll have to write a script to populate the data fields.

**Comment by sheyd** [comment]
Updated title to reflect the table we actually created.
