### ISSUE TITLE
Active Users missing from customer.io mailing list

### ISSUE THREAD

**Issue by jamjensen** [DoSomething/quasar#371]
_BUG_
-------------------
#### UPDATE 6/29 --
While ingesting updated Northstar records into the users table we overwrote customer_io_subscription_status, which resulted in nearly 1 million users losing there c.io status. 

The focus of this ticket is to now: 
1. track the backfill of c.io subscription status from the `c_io_export_fix_missing` -- which is a table created from a c.io csv export and includes the latest c.io subscription status, northstar_id, email address, subscription timestamp for every user in c.io. 
2. Document differences between the total number of members that are listed as subscribed in customer.io and the number of members in quasar who's `customer_io_subscription_status` = 'subscribed'.

-----------------------
_Pre 6/29 Focus of this ticket_

#### Current Behavior

1. There are 3,003,583 members in customer.io that are listed as `subscribed`, but there are only 2,978,609 members with customer_io_subscription_status as `subscribed` in Quasar.users -- which is 24,974 less than total in c.io. 

2. There are 13,417 accounts created with source as phoenix-oauth (since May 12th) that are subscribed to customer_io but lack subscription status in Quasar.  When I spot checked over a dozen random records, they were all subscribed to our c.io list. 

#### Why This Matters
Since they do not have a subscription status, these users are not included in our active member count. 

#### Relevant Screenshots + Links
- sql query to find users missing c.io status based on source: 
```select email, northstar_id_source_name, northstar_created_at_timestamp
from quasar.users
where customer_io_subscription_status IS NULL
and northstar_id_source_name = 'phoenix-oauth'
and northstar_created_at_timestamp >= '2017-05-12'
```

**Comment by sheyd** [comment]
@jamjensen I've run an export of all users from c.io and will upload to Quasar as a separate table to diff/reconcile against in the AM.

**Comment by sheyd** [comment]
The backfill is done. @jamjensen Do you want to track the 40K excess users (confirmed they still exist) in this ticket or another one?

**Comment by sheyd** [comment]
I've backfill/updated all of the missing c.io subscription_status, c_io_subscribe_timestamp, and c_io_unsubscribe_timestamp fields in the users table from the c.io user export performed yesterday AM.

**Comment by jamjensen** [comment]
Now that the backfill of all c.io subscription status from the `c_io_export_fix_missing` table into the `users` is complete, here is an update on number of records in `users` with subscription status = 'subscribed'. 

- Number of members in `users` with subscription status = 'subscribed': 3,041,253
- Number of members in `c_io_export_fix_missing` with unsubscribed = 'FALSE': 3,007,219
- Diff: 34,034

Number of users in the `users` table with cio_subscription_status = 'subscribed` that are not in the `c_io_export_fix_missing` table: 37,989
- query: `select count(distinct u.northstar_id), u.northstar_id_source_name
from users u
left join c_io_export_fix_missing cio
on u.northstar_id = cio.id
where cio.id IS NULL
and u.customer_io_subscription_status = 'subscribed'
group by u.northstar_id_source_name;`

**Comment by jamjensen** [comment]
### Update 7/10 
- Customer.io UI displays 3,028,574 members subscribed and querying `users` table displays 3,064,792 with customer io status = `subscribed`. 

### Next Steps
- [ ] @sheyd download csv of all members with unsubscribed = false from customer.io and put this info into a table so that I can isolate subscribed members in `users` that are missing from our c.io list
- [ ] @jamjensen create csv of members with`customer_io_subscription_status` = subscribed but who are missing from c.io
- [ ] @sheyd format csv and import to c.io

**Comment by jamjensen** [comment]
Update from @sheyd on c.io tables in mysql: 
https://dosomething.slack.com/archives/C0FP51V2T/p1499807914058376

**Comment by jamjensen** [comment]
**Update 7/13**
- users_c_io_count:  3,068,809 members with `customer_io_subscription_status` = 'subscribed' 
- c_io_export_071117: 3,007,219 members with `unsubscribed` = 'false' 
- diff: 61,590

- users in quasar not in c.io: 72,382
- count of inner join users and c_io_export: 2,996,427
