### ISSUE TITLE
Set Up Test Data Infrastructure

### ISSUE THREAD

**Issue by namimody** [DoSomething/quasar#39]
Create a Thor like environment where we can test new data set ups without the possibility of messing up or losing data.

BLOCKER to https://github.com/DoSomething/quasar/issues/37

**Comment by namimody** [comment]
@sheyd is this redundant to #46, #45, #47 and #50? If so, feel free to close. THanks!

**Comment by sheyd** [comment]
Yes, deprecated by all those.
