### ISSUE TITLE
Set Up Infrastructure for MC Data

### ISSUE THREAD

**Issue by namimody** [DoSomething/quasar#40]
In order to store constantly refreshed MC data in a warehouse vs. pinging their API, we need to set up an infrastructure.

@sheyd feel free to elaborate here and let me know if this needs to be parsed out into more tickets.

**Comment by namimody** [comment]
@sheyd To clarify, this is different than the test environment, yes?

**Comment by sheyd** [comment]
Also, yes, redundant.
