### ISSUE TITLE
Creating DB Replica from Mobile Commons

### ISSUE THREAD

**Issue by sheyd** [DoSomething/quasar#49]
- [x] Verify secure tunnel works
- [ ] MC sets up Slave DB (Check with Travis on 5/11 for timeline on completion)
- [ ] @sheyd need to get MC Slave DB credentials
- [ ] Quasar team test Slave DB

**Comment by sheyd** [comment]
Tunnel details on our end sent to Mobile Commons. Waiting on response from Travis.

**Comment by sheyd** [comment]
Update from Travis. He's still working on it.

**Comment by sheyd** [comment]
Travis e-mailed. He'll send over info for their side of the tunnel when it's setup. I'll follow up with him the week of 3/14 when I'm back from vacation to see how things are going.

**Comment by jessleenyc** [comment]
Deprecated
