### ISSUE TITLE
Document Northstar Architecture and Setup

### ISSUE THREAD

**Issue by sheyd** [DoSomething/quasar#5]
@sheyd, make sure you document data infrastructure side (i.e. Mongo setup and Logging).

**Comment by namimody** [comment]
Hi @DFurnes! Would you consider this complete? If not, how much work is left and what is the timeline? Thanks!

**Comment by DFurnes** [comment]
Yeah, I think we can mark this as closed. :hammer:

**Comment by DFurnes** [comment]
Well, my end at least. I can't speak to @sheyd's self-assigned portion in the issue description.
