### ISSUE TITLE
Can Mobile Commons integrate their CRM with Northstar the way that they integrate with Salesforce?

### ISSUE THREAD

**Issue by namimody** [DoSomething/quasar#51]

**Comment by DFurnes** [comment]
Here's MobileCommons' [documentation on CRM integration](https://mobilecommons.zendesk.com/hc/en-us/articles/202052354-Data-Sync). I'm not 100% sure whether or not this happens in realtime. From their documentation, it seems like they _might_ be able to sync profile data in real-time if the user texts in to 38383, but will only import data added directly to our "CRM" (Northstar) nightly...

> _Path 1: User texts to your organization_
> 
> Our system compares the information in the text against your database.
>  - If the user’s record is found in your database...we update it with the mobile number, and update Mobile > Commons with any additional information (e.g. name & address).
>  - If the user’s record is not found in your database.... we add the person andoptionally send them a welcome email.
>  
> 
> _Path 2: The user opts in through your existing CRM_
> 
> Each night, we import all new records in your CRM which have a valid mobile number.
>  - These people are opted in for text alerts and receive a welcome text the next day.
>  - You can choose to opt‐in ALL constituents with a mobile number, or just users who check a “Send Text Alerts” box.

Could be worth reaching out to our contact there to learn more.

**Comment by DFurnes** [comment]
Via Mal at Mobile Commons, "no"! :hammer:
