### ISSUE TITLE
How can we store up to date user status (subscribed/unsubscribed) in Northstar?

### ISSUE THREAD

**Issue by namimody** [DoSomething/quasar#52]

**Comment by DFurnes** [comment]
This relates to #51. From their documentation:

> - We set a flag in your CRM to indicate whether or not a user is opted in to mobile.
> - This field is updated immediately when the user opts-­‐in and again when they opt-­‐out by texting STOP.

**Comment by DFurnes** [comment]
So it's a no-go on their CRM sync, but I think we could still try to hack our own solution by having a "worker" process poll their [Profiles API](https://mobilecommons.zendesk.com/hc/en-us/articles/202052534-REST-API#ListAllProfiles) for updates every couple of minutes and then save those changes into Northstar.

**Comment by sheyd** [comment]
@DFurnes Is this at all related to the polling app you gave to Morgan to setup? I might be able to jump into getting this setup since it impacts Data platform.

**Comment by DFurnes** [comment]
@sheyd Yep, that's the one!

**Comment by sheyd** [comment]
Roger.

On Wed, Jun 22, 2016 at 11:30 AM, David Furnes <notifications@github.com>
wrote:

> @sheyd <https://github.com/sheyd> Yep, that's the one!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/DoSomething/quasar/issues/52#issuecomment-227781782>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEWeheSuWw1dYpPPkCwLM96J7Ia7cjWEks5qOVUogaJpZM4HZVYt>
> .
>



-- 
Sena Heydari
Director of Infrastructure Engineering, DoSomething.org
@alisinna

**Comment by sheyd** [comment]
DevOps repo implementation ticket: https://github.com/DoSomething/devops/issues/79

**Comment by sheyd** [comment]
Blocked by https://github.com/DoSomething/devops/issues/46

**Comment by sheyd** [comment]
@jessleenyc @DFurnes @mshmsh5000 Good news is we have the server up, and deployments working! 💃 

Things left to do:
* [ ] Update the `.env` file with a few more appropriate values.
* [ ] Make sure the Laravel Artisan Queueing and Daemonizing are working properly.
* [ ] Confirm that records are making it into Northstar.

**Comment by sheyd** [comment]
@DFurnes I think we can close this, right? Let's walk through the setup again next week when you're back so I make sure we didn't miss anything and this is production ready.

**Comment by DFurnes** [comment]
Yep, got sidetracked from this by some of the user data issues we're trying to wrap up. The remaining piece here is finishing up the "backfill" command, but probably safe to close and track issue on that repository (DoSomething/northstar-mobilecommonsd#9).

**Comment by jessleenyc** [comment]
tracking in northstar repo ^
