### ISSUE TITLE
Document and Automate Quantum Set Up

### ISSUE THREAD

**Issue by namimody** [DoSomething/quasar#55]

**Comment by sheyd** [comment]
Started Here:
https://github.com/DoSomething/quasar/wiki/Quantum-Test-Environment-Setup

**Comment by sheyd** [comment]
Hubble server setup and notes here:

https://github.com/DoSomething/quasar/wiki/Hubble-Systems-Architecture

**Comment by sheyd** [comment]
Super-seeded by Hubble documentation.
