### ISSUE TITLE
Migrate Data 1.0 Platform to Google Compute Cloud

### ISSUE THREAD

**Issue by sheyd** [DoSomething/quasar#66]
Current Data 1.0 Platform on AWS has some performance variance issues, and is hard to take backups of (we currently don't take any backups of our infrastructure). Given we have to keep Data 1.0 online for the foreseeable future, we need to automate the setup of the servers (partially done via #47, #46, #45), and setup a backup schedule. 

Google Cloud has proven to be a lot more stable, and require a lot less babysitting than AWS for a static environment like Data 1.0. The move will involve:

- [x] Production Data 1.0 DB Server
- [x] Production Data 1.0 Compute Server
- [x] Production Data 1.0 Admin/Dashboards Server (including User Count script from Joe)
- [x] Setup Data 1.0 DB Backup Schedule
- [x] Setup Slave Replication from Phoenix DB over VPN Tunnel
- [x] Slack Notifications on Job Failures

**Comment by namimody** [comment]
@sheyd can any of these be checked off?

**Comment by sheyd** [comment]
All done!
