### ISSUE TITLE
Spotcheck Mobile Commons Description Field

### ISSUE THREAD

**Issue by namimody** [DoSomething/quasar#80]
Current bug is certain campaigns have one number in the "description" field that doesn't actually represent the NID, like opt_in_path 11687

I think to do this we'll need a list of all the description fields and the names of the Mobile Commons campaigns they are associated with.

**Comment by nmccormick619** [comment]
Just waiting on Mobile Commons to remove the 'survey' campaign from the DB and then we can close this out!

**Comment by namimody** [comment]
Thanks for the update @nmccormick619! Are they removing the campaign completely or putting something specific in the "description" field?

**Comment by nmccormick619** [comment]
@namimody  - Removing the campaign completely so it won't be an issue!

**Comment by nmccormick619** [comment]
Update: Mobile Commons removed the description field but did not end up removing the campaign - so it will show up in a pull with NULLs as NID, RunNID. Closing this out.
