### ISSUE TITLE
Assess and Implement Tool for MailChimp User Data Import to Quasar

### ISSUE THREAD

**Issue by namimody** [DoSomething/quasar#81]
#### Issue:

We're having issues accessing "unsubscribe" members using the following Export API call:

https://us4.api.mailchimp.com/export/1.0/list?apikey=<redacted>&id=<redated>&status=unsubscribed.

The following error is returned:

Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 78 bytes) in /opt/mailchimp/10.8/app/models/MemberList.php on line 2812

#### Response from Mailchimp:

Adding additional query string parameters such as &status=unsubscribed result in a more taxing query on the API. We're sorry for any inconvenience this is causing.

About 1 year ago, MailChimp released API v3.0 into open beta:

http://devs.mailchimp.com/blog/api-v3-0-enters-open-beta/

Since then, previous versions of the API have been deprecated (to be completely discontinued in 9 months at the end of 2016), and we've included a corollary to the basic function of the export API through API v3.0's Batch Operations.

While we realize this is an issue with the Export API, to be transparent because the same result can be achieved through API v3.0 and the export API is set to be discontinued, we'll be working on improving 3.0 which we feel will have a more lasting impact for our users.

Moving forward, we'd recommend taking advantage of the new Batch Operation. We've got an excellent guide in our API documentation here:

http://developer.mailchimp.com/documentation/mailchimp/guides/how-to-use-batch-operations

To get a list of unsubscribed emails, API v3.0 users can create a batch of operations to GET /lists/{list_id}/members?status=subscribed

http://developer.mailchimp.com/documentation/mailchimp/reference/lists/members/#

**Comment by sheyd** [comment]
Did a quick assessment of the API and re-factor work, and this will likely take about a full sprint day to complete.

**Comment by sheyd** [comment]
Ticket open with Mailchimp. They've turned on some backend logging to get additional info on why batch submissions for member unsubscribes are not returning any results. Just sent some requests test data to Support.

**Comment by sheyd** [comment]
Yet another test response to MailChimp, since the output downloads I'm getting *still* aren't populated with data.

**Comment by sheyd** [comment]
API 3.0 MailChimp Support Final Response:
```

Hey Sena,

Thanks so much for writing in to us at support. I totally get how important it is to get batch operations working as expected, and I'd be happy to provide any assistance that I can with that. 

Taking a look at the endpoint that's being used in the "path" parameter for the batch operation, I notice that list id that's being given is 71893. When making API requests, the list ID that will need to be used is the unique list ID. That can be found in the account by clicking on the Lists section of the account > selecting the list that you're working with > clicking on List Name and Defaults http://screencast.com/t/gGmAeaI0W. The unique ID for the list will be under the "List ID" section. 

Once that unique list ID is found, you'll want to place it in the relative URL endpoint in the "path" parameter so that it looks like:

"path": "/lists/{unique_list_id}/members"

```

**Comment by sheyd** [comment]
We started the testing of Batch Processing v3.0 of the MailChimp API for unsubscribes. v1.0 of the API is going to be deprecated end of 2016. Based on what tool we use for MailChimp user-data imports for Quasar, we should assess at that time to re-visit this ticket if we're using custom ETL jobs, or close this ticket in favor of another tool.

**Comment by sheyd** [comment]
This ticket was formerly titled: Fix Broken Mailchimp API Call for Unsubscribes. This was with regards to Data 1.0

**Comment by sheyd** [comment]
The MailChimp v1.0 API broke again. With help from @mshmsh5000, we were able to figure out a solution to paginate through the v3.0 API without using batch processing. We still have to re-factor some code to paginate, set origin backfill date, and parse JSON fields to insert to DB, but this should go fairly quickly.

Sample URI request for reference:

**Comment by sheyd** [comment]
Testing out backfill from the last day before rolling into prod, but so far looking good!

**Comment by sheyd** [comment]
We've been hit by a bad stroke of luck, the MailChimp v3.0 API doesn't support pagination via the `offset` argument, like I thought it did. Misreading on my part, the `offset` only skips that number of records. 

The new approach I'm sanity checking with @mshmsh5000 would basically iterate over X number of records per Y hours, mimicking pagination going back in time bounded by earliest starting time and now.

**Comment by sheyd** [comment]
Refactored code for v3.0 of the API is working! Moving back to "Future" pipeline, since we have to re-visit for Quasar build-out which will have a separate backend.
