### ISSUE TITLE
Add Status "Undeliverable" to Mobile_User_Lookup Table

### ISSUE THREAD

**Issue by namimody** [DoSomething/quasar#83]
The Profile API includes users who status is “Undeliverable”, and we’re not tracking that in the `mobile_user_lookup` table right now -- let's add it as a column!

- [x] schema update
- [x] scraper script update
- [x] restart the backfill process

**Comment by sheyd** [comment]
`ALTER TABLE mobile_user_lookup add status varchar(255);`

Updated the table schema.

**Comment by sheyd** [comment]
Script tested and updated.

**Comment by sheyd** [comment]
Script deployed the Quantum and backfill process for 1 year restarted.
