### ISSUE TITLE
Find a RegEx to Check for Irregularities in Phone Numbers

### ISSUE THREAD

**Issue by namimody** [DoSomething/quasar#86]
Figure out nonstandard/invalid phone numbers within data set.
Then figure out where the bad numbers are coming from.

**Comment by DFurnes** [comment]
We currently perform ["simple" validation](https://github.com/DoSomething/phoenix/blob/bce57ab610a13428aabd71e8b6b8ce9d32846d76/lib/modules/dosomething/dosomething_user/dosomething_user.module#L175-L209) on Phoenix signups and referrals, and [sanitize input to only include numeric characters](https://github.com/DoSomething/phoenix/blob/bce57ab610a13428aabd71e8b6b8ce9d32846d76/lib/modules/dosomething/dosomething_user/dosomething_user.module#L1051-L1077) within Phoenix and [when saving to Northstar](https://github.com/DoSomething/northstar/blob/58e878b2b26179f9de7cad36a67f8832ad2d6013/app/Models/User.php#L170-L186). This may not always have been the case though.

**Comment by DFurnes** [comment]
We also do more [aggressive validation](https://github.com/Propaganistas/Laravel-Phone) in Voting App since we try to ensure that a phone number is valid _specifically_ in the given user's country code, although I'm not sure it's worth doing this everywhere at the risk of false negatives.

**Comment by sheyd** [comment]
@DFurnes I would love to use `libphonenumber` everywhere. In the meantime, using the following RegExp sequel statement `select * from mobile_user_lookup as m where m.phone_number NOT REGEXP '^[0-9]{1,13}$'`, I've found our super-long phone numbers (not the ridiculous ones that are less than that), and it seems most of the come from Niche imports. I backtracked this by finding the source_name for most was "DoSomething Developer" and doing a Mobile Commons lookup, and finding "source" as "Niche". This means there's various places in the pipeline we can correct for this. Not sure which is the most efficient. My initial thoughts are that we should probably make sure Northstar and Quasar/Data 1.0 are properly validated as sources of truth. On the Quasar/Data 1.0 side, we can always do corrective ETL, and scale that up. @DFurnes would you have any interest to use Quasar as a source of truth to verify daily new users post ETL-ingestion processing? Maybe that with shored up front-end checking?

**Comment by sheyd** [comment]
Closing this out. The max number of bad format numbers we have is about ~5000 at most. Focusing on this is a bit finding a solution for a non-existent problem, especially since Mobile Commons figures out the "undeliverable" part for us. Kicking this over until we get into Quasar Schema planning. We have some scope of problem now.

**Comment by DFurnes** [comment]
@sheyd :+1:

**Comment by namimody** [comment]
Thanks for looking into this so fast @DFurnes and @sheyd! I'm going to reopen and move to the Future Sprints milestone so this thought and work doesn't get buried. :+1:

**Comment by jessleenyc** [comment]
a more elegant solution perhaps: check mobile commons status on deliverability

**Comment by jessleenyc** [comment]
@sheyd we'll be getting their mobile commons status in northstar. cc @Bladt

**Comment by jessleenyc** [comment]
Closing - should be done in NS.
