### ISSUE TITLE
Automation for Mobile Commons Data ETL Process 

### ISSUE THREAD

**Issue by sheyd** [DoSomething/quasar#9]
Semi-Automate Mobile Common campaign ID ingestion from python script.

**Comment by sheyd** [comment]
Need to automate in Jenkins server the running of the `campaign_loader.py` script which needs the following arguments:

* backfill_hours
* nid
* campaign sms (1/0 for yes/no)
* campaign_run
* campaign_id
* opt in id
* opt in path web_alpha (1/0 for yes/no)

@Bladt `backfill_hours`, `nid`, `campaign sms`, and `campaign_id` are all clear for me. Can you shed some light on the other fields? Are they all fields pullable from Mobile Commons?

**Comment by namimody** [comment]
pulling in description field
