### ISSUE TITLE
Setting Up Metabase to Replace Data 1.0 Dashboards

### ISSUE THREAD

**Issue by sheyd** [DoSomething/quasar#91]
http://www.metabase.com/

**Comment by namimody** [comment]
Nami to look int: 
- [ ] saving dashboard views
- [ ] live connection to DB
- [ ] credential sharing process

**Comment by namimody** [comment]
Looks like a great option! To get this going, here's what needs to happen:

- [ ] rearrange columns in spreadsheet to be a bit more UX friendly
- [ ] set up email pulse
- [ ] set up Slack pulse
- [ ] share credentials with campaigns team and others
- [ ] create quick tutorial on how Metabase should be used

**Comment by namimody** [comment]
Not gonna use Metabase, closing.
