### ISSUE TITLE
Create and Automate "Mobile Master Look Up" Table

### ISSUE THREAD

**Issue by namimody** [DoSomething/quasar#96]
create and automate mobile master look up table from query:

```
select *
from users_and_activities.mobile_subscriptions ms 
    left outer join users_and_activities.mobile_campaign_id_lookup mc
        on ms.opt_in_id = mc.opt_in_path_id
    left outer join dosomething.node n
        on n.nid = mc.run_nid
    left outer join mobile_user_lookup mu
        on mu.phone_number = ms.phone_number
```

**Comment by sheyd** [comment]
This query results in duplicate column names which we have to make unique in order to have them stored in a table. This requires flushing out the `select` portion of the the query to use an `as` clause` that's renamed.

**Comment by sheyd** [comment]
The table creation query is running successfully. Full query is in Slack channel. Going to get #97 finished up since we want the UID field in the master lookup table.

**Comment by sheyd** [comment]
Done.
